import type {
  FestivalConfig,
  FestivalTask,
  FestivalScene,
  FestivalItem,
  ExchangeItem,
  FestivalLeaderboardEntry,
} from './types';

const NOW = Date.now();
const ONE_WEEK = 7 * 24 * 60 * 60 * 1000;
const TWO_WEEKS = 14 * 24 * 60 * 60 * 1000;

export const FESTIVALS: FestivalConfig[] = [
  {
    id: 'spring_kite_festival_2026',
    name: '春日风筝节',
    theme: 'spring',
    description: '春暖花开，万物复苏！参与春日风筝节，收集樱花花瓣，解锁限定奖励！',
    icon: '🌸',
    banner: 'spring',
    primaryColor: '#ec4899',
    secondaryColor: '#f472b6',
    startDate: NOW - ONE_WEEK,
    endDate: NOW + ONE_WEEK,
    currencyId: 'cherry_blossom_petal',
  },
  {
    id: 'summer_wind_festival_2026',
    name: '夏日风之祭',
    theme: 'summer',
    description: '炎炎夏日，乘风破浪！收集海风贝壳，在夏日专属场景中挑战最高分！',
    icon: '🌊',
    banner: 'summer',
    primaryColor: '#0ea5e9',
    secondaryColor: '#38bdf8',
    startDate: NOW + TWO_WEEKS,
    endDate: NOW + TWO_WEEKS + ONE_WEEK,
    currencyId: 'ocean_shell',
  },
];

export const FESTIVAL_TASKS: FestivalTask[] = [
  {
    id: 'daily_play_3',
    festivalId: 'spring_kite_festival_2026',
    type: 'daily',
    title: '每日飞行',
    description: '完成3次飞行',
    target: 3,
    progressKey: 'flights_completed',
    dailyReset: true,
    rewards: [
      { type: 'coin', amount: 200, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 10, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 1,
  },
  {
    id: 'daily_score_2000',
    festivalId: 'spring_kite_festival_2026',
    type: 'daily',
    title: '得分挑战',
    description: '单次飞行获得2000分以上',
    target: 1,
    progressKey: 'single_score_2000',
    dailyReset: true,
    rewards: [
      { type: 'coin', amount: 300, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 15, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 2,
  },
  {
    id: 'daily_distance_500',
    festivalId: 'spring_kite_festival_2026',
    type: 'daily',
    title: '远航挑战',
    description: '单次飞行距离达到500米',
    target: 1,
    progressKey: 'single_distance_500',
    dailyReset: true,
    rewards: [
      { type: 'coin', amount: 250, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 12, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 3,
  },
  {
    id: 'daily_no_collision',
    festivalId: 'spring_kite_festival_2026',
    type: 'daily',
    title: '完美飞行',
    description: '完成1次无碰撞飞行',
    target: 1,
    progressKey: 'no_collision_flights',
    dailyReset: true,
    rewards: [
      { type: 'coin', amount: 400, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 20, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 4,
  },
  {
    id: 'cumulative_flights_20',
    festivalId: 'spring_kite_festival_2026',
    type: 'cumulative',
    title: '飞行达人',
    description: '累计完成20次飞行',
    target: 20,
    progressKey: 'total_flights',
    rewards: [
      { type: 'coin', amount: 1000, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 50, name: '樱花花瓣', icon: '🌸' },
      { type: 'badge', id: 'flight_master', amount: 1, name: '飞行达人徽章', icon: '🎖️' },
    ],
    order: 10,
  },
  {
    id: 'cumulative_score_50000',
    festivalId: 'spring_kite_festival_2026',
    type: 'cumulative',
    title: '高分王者',
    description: '累计获得50000分',
    target: 50000,
    progressKey: 'total_score',
    rewards: [
      { type: 'coin', amount: 2000, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 100, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 11,
  },
  {
    id: 'cumulative_air_current_100',
    festivalId: 'spring_kite_festival_2026',
    type: 'cumulative',
    title: '气流猎手',
    description: '累计捕获100次上升气流',
    target: 100,
    progressKey: 'total_air_currents',
    rewards: [
      { type: 'coin', amount: 800, name: '金币', icon: '🪙' },
      { type: 'item', id: 'cherry_blossom_petal', amount: 40, name: '樱花花瓣', icon: '🌸' },
    ],
    order: 12,
  },
  {
    id: 'special_spring_scene',
    festivalId: 'spring_kite_festival_2026',
    type: 'special',
    title: '春日探索者',
    description: '在春日樱花园场景完成5次飞行',
    target: 5,
    progressKey: 'spring_scene_flights',
    rewards: [
      { type: 'coin', amount: 1500, name: '金币', icon: '🪙' },
      { type: 'item', id: 'sakura_kite_sail', amount: 1, name: '樱花风筝面', icon: '🪁' },
    ],
    order: 20,
  },
  {
    id: 'special_leaderboard_top10',
    festivalId: 'spring_kite_festival_2026',
    type: 'special',
    title: '排行榜精英',
    description: '进入节日排行榜前10名',
    target: 1,
    progressKey: 'leaderboard_top10',
    rewards: [
      { type: 'coin', amount: 3000, name: '金币', icon: '🪙' },
      { type: 'item', id: 'golden_cherry_charm', amount: 1, name: '黄金樱花护符', icon: '🏆' },
      { type: 'badge', id: 'top_10_flyer', amount: 1, name: '十大飞手徽章', icon: '🥇' },
    ],
    order: 21,
  },
];

export const FESTIVAL_SCENES: FestivalScene[] = [
  {
    id: 'scene_spring_sakura',
    festivalId: 'spring_kite_festival_2026',
    name: '春日樱花园',
    description: '樱花纷飞的春日花园，上升气流更频繁，得分+20%',
    icon: '🌸',
    weatherTheme: 'spring',
    backgroundGradient: ['#fce7f3', '#fbcfe8'],
    particleEffect: 'sakura_petals',
    scoreMultiplier: 1.2,
    coinMultiplier: 1.1,
    specialEvent: 'random_cherry_bonus',
    worldSize: 2000,
    gravity: 0.012,
    airCurrentSpawnRate: 1.3,
    minAirCurrentStrength: 0.8,
    maxAirCurrentStrength: 1.5,
    buildingDensity: 0.5,
    turbulenceLevel: 0.1,
    cloudCoverage: 0.2,
    unlocked: true,
  },
  {
    id: 'scene_spring_bamboo',
    festivalId: 'spring_kite_festival_2026',
    name: '竹林清风',
    description: '幽静的竹林深处，气流稳定但建筑密集，适合挑战飞行技术',
    icon: '🎋',
    weatherTheme: 'bamboo',
    backgroundGradient: ['#d1fae5', '#a7f3d0'],
    particleEffect: 'bamboo_leaves',
    scoreMultiplier: 1.3,
    coinMultiplier: 1.2,
    specialEvent: 'bamboo_wind_gust',
    worldSize: 1800,
    gravity: 0.014,
    airCurrentSpawnRate: 1.0,
    minAirCurrentStrength: 1.0,
    maxAirCurrentStrength: 1.8,
    buildingDensity: 0.8,
    turbulenceLevel: 0.2,
    cloudCoverage: 0.3,
    unlocked: false,
    unlockCost: 100,
  },
  {
    id: 'scene_spring_river',
    festivalId: 'spring_kite_festival_2026',
    name: '春江花月夜',
    description: '河畔的春日黄昏，距离加成显著，但气流变化剧烈',
    icon: '🌊',
    weatherTheme: 'riverside',
    backgroundGradient: ['#fef3c7', '#fde68a'],
    particleEffect: 'river_mist',
    scoreMultiplier: 1.5,
    coinMultiplier: 1.3,
    specialEvent: 'sunset_bonus_wave',
    worldSize: 2500,
    gravity: 0.013,
    airCurrentSpawnRate: 1.5,
    minAirCurrentStrength: 0.5,
    maxAirCurrentStrength: 2.2,
    buildingDensity: 0.4,
    turbulenceLevel: 0.5,
    cloudCoverage: 0.5,
    unlocked: false,
    unlockCost: 200,
  },
];

export const FESTIVAL_ITEMS: FestivalItem[] = [
  {
    id: 'cherry_blossom_petal',
    festivalId: 'spring_kite_festival_2026',
    name: '樱花花瓣',
    description: '春日风筝节的专属货币，可用于兑换奖励',
    category: 'currency',
    rarity: 'common',
    icon: '🌸',
    stackable: true,
    tradable: false,
  },
  {
    id: 'spring_breeze_potion',
    festivalId: 'spring_kite_festival_2026',
    name: '春风药剂',
    description: '使用后下一局飞行得分+30%，持续一局',
    category: 'buff',
    rarity: 'rare',
    icon: '🧪',
    buffEffect: {
      type: 'score',
      value: 0.3,
      duration: 1,
    },
    stackable: true,
    tradable: false,
  },
  {
    id: 'wind_charm',
    festivalId: 'spring_kite_festival_2026',
    name: '风之护符',
    description: '使用后下一局飞行稳定性+25%，持续一局',
    category: 'buff',
    rarity: 'uncommon',
    icon: '🎐',
    buffEffect: {
      type: 'stability',
      value: 0.25,
      duration: 1,
    },
    stackable: true,
    tradable: false,
  },
  {
    id: 'distance_booster',
    festivalId: 'spring_kite_festival_2026',
    name: '远航推进器',
    description: '使用后下一局飞行距离加成+40%，持续一局',
    category: 'buff',
    rarity: 'rare',
    icon: '🚀',
    buffEffect: {
      type: 'distance',
      value: 0.4,
      duration: 1,
    },
    stackable: true,
    tradable: false,
  },
  {
    id: 'height_lifter',
    festivalId: 'spring_kite_festival_2026',
    name: '高度提升器',
    description: '使用后下一局飞行最大高度加成+35%，持续一局',
    category: 'buff',
    rarity: 'rare',
    icon: '⬆️',
    buffEffect: {
      type: 'height',
      value: 0.35,
      duration: 1,
    },
    stackable: true,
    tradable: false,
  },
  {
    id: 'combo_amplifier',
    festivalId: 'spring_kite_festival_2026',
    name: '连击增幅器',
    description: '使用后下一局连击倍率上限+50%，持续一局',
    category: 'buff',
    rarity: 'epic',
    icon: '⚡',
    buffEffect: {
      type: 'combo',
      value: 0.5,
      duration: 1,
    },
    stackable: true,
    tradable: false,
  },
  {
    id: 'sakura_kite_sail',
    festivalId: 'spring_kite_festival_2026',
    name: '樱花风筝面',
    description: '春日限定风筝面，装备后永久增加5%得分加成',
    category: 'exclusive',
    rarity: 'festival',
    icon: '🪁',
    visualEffect: 'sakura_pattern',
    stackable: false,
    tradable: false,
  },
  {
    id: 'golden_cherry_charm',
    festivalId: 'spring_kite_festival_2026',
    name: '黄金樱花护符',
    description: '节日排行榜前10名专属奖励，象征荣耀与实力',
    category: 'exclusive',
    rarity: 'legendary',
    icon: '🏆',
    stackable: false,
    tradable: false,
  },
];

export const EXCHANGE_ITEMS: ExchangeItem[] = [
  {
    id: 'exchange_coin_500',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'coin', amount: 500, name: '金币', icon: '🪙' },
    cost: 20,
    dailyLimit: 5,
  },
  {
    id: 'exchange_spring_breeze',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'spring_breeze_potion', amount: 1, name: '春风药剂', icon: '🧪' },
    cost: 50,
    dailyLimit: 3,
  },
  {
    id: 'exchange_wind_charm',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'wind_charm', amount: 1, name: '风之护符', icon: '🎐' },
    cost: 40,
    dailyLimit: 3,
  },
  {
    id: 'exchange_distance_booster',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'distance_booster', amount: 1, name: '远航推进器', icon: '🚀' },
    cost: 60,
    dailyLimit: 2,
  },
  {
    id: 'exchange_height_lifter',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'height_lifter', amount: 1, name: '高度提升器', icon: '⬆️' },
    cost: 60,
    dailyLimit: 2,
  },
  {
    id: 'exchange_combo_amplifier',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'combo_amplifier', amount: 1, name: '连击增幅器', icon: '⚡' },
    cost: 100,
    limitPerPlayer: 5,
  },
  {
    id: 'exchange_sakura_sail',
    festivalId: 'spring_kite_festival_2026',
    reward: { type: 'item', id: 'sakura_kite_sail', amount: 1, name: '樱花风筝面', icon: '🪁' },
    cost: 300,
    limitPerPlayer: 1,
  },
];

export const NPC_LEADERBOARD: Omit<FestivalLeaderboardEntry, 'rank' | 'isPlayer'>[] = [
  { playerId: 'npc_1', playerName: '云端漫步者', score: 98500, festivalCurrency: 890, completedTasks: 12, badgeCount: 5 },
  { playerId: 'npc_2', playerName: '风筝匠人', score: 87200, festivalCurrency: 760, completedTasks: 11, badgeCount: 4 },
  { playerId: 'npc_3', playerName: '风之使者', score: 76800, festivalCurrency: 680, completedTasks: 10, badgeCount: 4 },
  { playerId: 'npc_4', playerName: '春日精灵', score: 65400, festivalCurrency: 590, completedTasks: 9, badgeCount: 3 },
  { playerId: 'npc_5', playerName: '影子追踪者', score: 54300, festivalCurrency: 520, completedTasks: 8, badgeCount: 3 },
  { playerId: 'npc_6', playerName: '飞翔少年', score: 43200, festivalCurrency: 450, completedTasks: 7, badgeCount: 2 },
  { playerId: 'npc_7', playerName: '云端梦想家', score: 38900, festivalCurrency: 380, completedTasks: 6, badgeCount: 2 },
  { playerId: 'npc_8', playerName: '风语者', score: 32100, festivalCurrency: 320, completedTasks: 5, badgeCount: 1 },
  { playerId: 'npc_9', playerName: '纸鸢高手', score: 27800, festivalCurrency: 270, completedTasks: 5, badgeCount: 1 },
  { playerId: 'npc_10', playerName: '樱花骑士', score: 23400, festivalCurrency: 230, completedTasks: 4, badgeCount: 1 },
  { playerId: 'npc_11', playerName: '蓝天翱翔', score: 19200, festivalCurrency: 190, completedTasks: 3, badgeCount: 0 },
  { playerId: 'npc_12', playerName: '微风使者', score: 15600, festivalCurrency: 160, completedTasks: 3, badgeCount: 0 },
  { playerId: 'npc_13', playerName: '飞翔的梦', score: 12300, festivalCurrency: 130, completedTasks: 2, badgeCount: 0 },
  { playerId: 'npc_14', playerName: '春日萌新', score: 8900, festivalCurrency: 90, completedTasks: 2, badgeCount: 0 },
  { playerId: 'npc_15', playerName: '风筝新手', score: 5400, festivalCurrency: 60, completedTasks: 1, badgeCount: 0 },
];
