import type { Achievement, PilotProfile, JourneyState, Title } from './types';

const ACHIEVEMENT_DEFS: Array<Omit<Achievement, 'unlocked' | 'unlockedAt' | 'progress'>> = [
  {
    id: 'first_flight',
    name: '初次起飞',
    description: '完成第一次风筝飞行',
    icon: '🪁',
    category: 'special',
    rarity: 'common',
    condition: { type: 'total_flights', target: 1 },
    rewardCoins: 50,
    maxProgress: 1,
  },
  {
    id: 'rookie_pilot',
    name: '菜鸟飞行员',
    description: '累计完成 10 次飞行',
    icon: '🎯',
    category: 'special',
    rarity: 'common',
    condition: { type: 'total_flights', target: 10 },
    rewardCoins: 100,
    maxProgress: 10,
  },
  {
    id: 'veteran_pilot',
    name: '资深飞行员',
    description: '累计完成 100 次飞行',
    icon: '🏅',
    category: 'special',
    rarity: 'rare',
    condition: { type: 'total_flights', target: 100 },
    rewardCoins: 500,
    maxProgress: 100,
  },
  {
    id: 'legendary_pilot',
    name: '传奇飞行家',
    description: '累计完成 500 次飞行',
    icon: '👑',
    category: 'special',
    rarity: 'legendary',
    condition: { type: 'total_flights', target: 500 },
    rewardCoins: 2000,
    maxProgress: 500,
  },
  {
    id: 'short_journey',
    name: '短途旅行',
    description: '累计飞行距离达到 1000 米',
    icon: '🛤️',
    category: 'distance',
    rarity: 'common',
    condition: { type: 'total_distance', target: 1000 },
    rewardCoins: 80,
    maxProgress: 1000,
  },
  {
    id: 'medium_journey',
    name: '中距离航行',
    description: '累计飞行距离达到 10000 米',
    icon: '🌉',
    category: 'distance',
    rarity: 'rare',
    condition: { type: 'total_distance', target: 10000 },
    rewardCoins: 300,
    maxProgress: 10000,
  },
  {
    id: 'long_journey',
    name: '长途跋涉',
    description: '累计飞行距离达到 50000 米',
    icon: '🏔️',
    category: 'distance',
    rarity: 'epic',
    condition: { type: 'total_distance', target: 50000 },
    rewardCoins: 800,
    maxProgress: 50000,
  },
  {
    id: 'ultra_journey',
    name: '环球飞行',
    description: '累计飞行距离达到 200000 米',
    icon: '🌍',
    category: 'distance',
    rarity: 'legendary',
    condition: { type: 'total_distance', target: 200000 },
    rewardCoins: 3000,
    maxProgress: 200000,
  },
  {
    id: 'single_distance_500',
    name: '五百米冲刺',
    description: '单次飞行距离达到 500 米',
    icon: '💨',
    category: 'distance',
    rarity: 'common',
    condition: { type: 'max_distance_single', target: 500 },
    rewardCoins: 60,
    maxProgress: 500,
  },
  {
    id: 'single_distance_2000',
    name: '两千米跨越',
    description: '单次飞行距离达到 2000 米',
    icon: '🚀',
    category: 'distance',
    rarity: 'rare',
    condition: { type: 'max_distance_single', target: 2000 },
    rewardCoins: 250,
    maxProgress: 2000,
  },
  {
    id: 'single_distance_5000',
    name: '五千米奇迹',
    description: '单次飞行距离达到 5000 米',
    icon: '☄️',
    category: 'distance',
    rarity: 'epic',
    condition: { type: 'max_distance_single', target: 5000 },
    rewardCoins: 1000,
    maxProgress: 5000,
  },
  {
    id: 'sky_explorer',
    name: '天空探索者',
    description: '达到 200 米的高度',
    icon: '🏔️',
    category: 'height',
    rarity: 'common',
    condition: { type: 'max_height', target: 200 },
    rewardCoins: 80,
    maxProgress: 200,
  },
  {
    id: 'cloud_dancer',
    name: '云端舞者',
    description: '达到 350 米的高度',
    icon: '☁️',
    category: 'height',
    rarity: 'rare',
    condition: { type: 'max_height', target: 350 },
    rewardCoins: 300,
    maxProgress: 350,
  },
  {
    id: 'strato_boundary',
    name: '平流层边界',
    description: '达到 500 米的高度',
    icon: '🌌',
    category: 'height',
    rarity: 'epic',
    condition: { type: 'max_height', target: 500 },
    rewardCoins: 800,
    maxProgress: 500,
  },
  {
    id: 'near_space',
    name: '近空飞行',
    description: '达到 800 米的高度',
    icon: '🛰️',
    category: 'height',
    rarity: 'legendary',
    condition: { type: 'max_height', target: 800 },
    rewardCoins: 2500,
    maxProgress: 800,
  },
  {
    id: 'score_1000',
    name: '千分达成',
    description: '单次飞行得分达到 1000 分',
    icon: '💯',
    category: 'score',
    rarity: 'common',
    condition: { type: 'max_score_single', target: 1000 },
    rewardCoins: 60,
    maxProgress: 1000,
  },
  {
    id: 'score_5000',
    name: '五千分能手',
    description: '单次飞行得分达到 5000 分',
    icon: '🎖️',
    category: 'score',
    rarity: 'rare',
    condition: { type: 'max_score_single', target: 5000 },
    rewardCoins: 250,
    maxProgress: 5000,
  },
  {
    id: 'score_15000',
    name: '一万五千分大师',
    description: '单次飞行得分达到 15000 分',
    icon: '🏆',
    category: 'score',
    rarity: 'epic',
    condition: { type: 'max_score_single', target: 15000 },
    rewardCoins: 800,
    maxProgress: 15000,
  },
  {
    id: 'score_50000',
    name: '五万分传奇',
    description: '单次飞行得分达到 50000 分',
    icon: '🌟',
    category: 'score',
    rarity: 'legendary',
    condition: { type: 'max_score_single', target: 50000 },
    rewardCoins: 3000,
    maxProgress: 50000,
  },
  {
    id: 'total_score_10000',
    name: '万分积累',
    description: '累计总得分达到 10000 分',
    icon: '📊',
    category: 'score',
    rarity: 'common',
    condition: { type: 'total_score', target: 10000 },
    rewardCoins: 100,
    maxProgress: 10000,
  },
  {
    id: 'total_score_100000',
    name: '十万分俱乐部',
    description: '累计总得分达到 100000 分',
    icon: '💎',
    category: 'score',
    rarity: 'epic',
    condition: { type: 'total_score', target: 100000 },
    rewardCoins: 1000,
    maxProgress: 100000,
  },
  {
    id: 'aircurrent_hunter_10',
    name: '气流猎人',
    description: '累计捕获 10 个上升气流',
    icon: '🌀',
    category: 'skill',
    rarity: 'common',
    condition: { type: 'aircurrent_total', target: 10 },
    rewardCoins: 50,
    maxProgress: 10,
  },
  {
    id: 'aircurrent_hunter_100',
    name: '气流大师',
    description: '累计捕获 100 个上升气流',
    icon: '🌪️',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'aircurrent_total', target: 100 },
    rewardCoins: 250,
    maxProgress: 100,
  },
  {
    id: 'aircurrent_hunter_500',
    name: '气流传奇',
    description: '累计捕获 500 个上升气流',
    icon: '🌬️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'aircurrent_total', target: 500 },
    rewardCoins: 800,
    maxProgress: 500,
  },
  {
    id: 'perfect_5',
    name: '无瑕飞行',
    description: '完成 5 次零碰撞飞行',
    icon: '✨',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'perfect_flights', target: 5 },
    rewardCoins: 200,
    maxProgress: 5,
  },
  {
    id: 'perfect_20',
    name: '精准大师',
    description: '完成 20 次零碰撞飞行',
    icon: '💫',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'perfect_flights', target: 20 },
    rewardCoins: 600,
    maxProgress: 20,
  },
  {
    id: 'streak_5',
    name: '连胜五次',
    description: '连续完成 5 次零碰撞飞行',
    icon: '🔥',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'consecutive_no_collision', target: 5 },
    rewardCoins: 250,
    maxProgress: 5,
  },
  {
    id: 'streak_15',
    name: '连续完美',
    description: '连续完成 15 次零碰撞飞行',
    icon: '☀️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'consecutive_no_collision', target: 15 },
    rewardCoins: 800,
    maxProgress: 15,
  },
  {
    id: 'all_modes',
    name: '全能飞行员',
    description: '体验全部 5 种飞行模式',
    icon: '🎪',
    category: 'exploration',
    rarity: 'epic',
    condition: { type: 'modes_unlocked', target: 5 },
    rewardCoins: 500,
    maxProgress: 5,
  },
  {
    id: 'weather_adventurer',
    name: '天气冒险家',
    description: '在 4 种不同天气条件下飞行',
    icon: '🌤️',
    category: 'exploration',
    rarity: 'rare',
    condition: { type: 'weather_experienced', target: 4 },
    rewardCoins: 300,
    maxProgress: 4,
  },
  {
    id: 'zero_collision_1000',
    name: '千里无碰撞',
    description: '零碰撞累计飞行 1000 米',
    icon: '🎯',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'zero_collision_distance', target: 1000 },
    rewardCoins: 300,
    maxProgress: 1000,
  },
  {
    id: 'zero_collision_5000',
    name: '完美远航',
    description: '零碰撞累计飞行 5000 米',
    icon: '🎖️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'zero_collision_distance', target: 5000 },
    rewardCoins: 800,
    maxProgress: 5000,
  },
  {
    id: 'realtime_height_100',
    name: '百米突破',
    description: '飞行中达到 100 米高度',
    icon: '🎯',
    category: 'height',
    rarity: 'common',
    condition: { type: 'current_height_realtime', target: 100 },
    rewardCoins: 50,
    maxProgress: 100,
  },
  {
    id: 'realtime_height_150',
    name: '高空飞行',
    description: '飞行中达到 150 米高度',
    icon: '🏔️',
    category: 'height',
    rarity: 'common',
    condition: { type: 'current_height_realtime', target: 150 },
    rewardCoins: 100,
    maxProgress: 150,
  },
  {
    id: 'realtime_height_250',
    name: '云层之上',
    description: '飞行中达到 250 米高度',
    icon: '☁️',
    category: 'height',
    rarity: 'rare',
    condition: { type: 'current_height_realtime', target: 250 },
    rewardCoins: 200,
    maxProgress: 250,
  },
  {
    id: 'realtime_height_400',
    name: '平流层边缘',
    description: '飞行中达到 400 米高度',
    icon: '🌌',
    category: 'height',
    rarity: 'epic',
    condition: { type: 'current_height_realtime', target: 400 },
    rewardCoins: 500,
    maxProgress: 400,
  },
  {
    id: 'realtime_height_600',
    name: '临近空间',
    description: '飞行中达到 600 米高度',
    icon: '🛰️',
    category: 'height',
    rarity: 'legendary',
    condition: { type: 'current_height_realtime', target: 600 },
    rewardCoins: 1500,
    maxProgress: 600,
  },
  {
    id: 'realtime_score_500',
    name: '五百分达成',
    description: '单局飞行中实时得分达到 500 分',
    icon: '💯',
    category: 'score',
    rarity: 'common',
    condition: { type: 'current_score_realtime', target: 500 },
    rewardCoins: 50,
    maxProgress: 500,
  },
  {
    id: 'realtime_score_2000',
    name: '两千分达人',
    description: '单局飞行中实时得分达到 2000 分',
    icon: '🎖️',
    category: 'score',
    rarity: 'rare',
    condition: { type: 'current_score_realtime', target: 2000 },
    rewardCoins: 200,
    maxProgress: 2000,
  },
  {
    id: 'realtime_score_8000',
    name: '八千分高手',
    description: '单局飞行中实时得分达到 8000 分',
    icon: '🏆',
    category: 'score',
    rarity: 'epic',
    condition: { type: 'current_score_realtime', target: 8000 },
    rewardCoins: 600,
    maxProgress: 8000,
  },
  {
    id: 'realtime_score_25000',
    name: '两万五千分传奇',
    description: '单局飞行中实时得分达到 25000 分',
    icon: '🌟',
    category: 'score',
    rarity: 'legendary',
    condition: { type: 'current_score_realtime', target: 25000 },
    rewardCoins: 2000,
    maxProgress: 25000,
  },
  {
    id: 'realtime_distance_300',
    name: '三百米冲刺',
    description: '单局飞行中实时距离达到 300 米',
    icon: '💨',
    category: 'distance',
    rarity: 'common',
    condition: { type: 'current_distance_realtime', target: 300 },
    rewardCoins: 50,
    maxProgress: 300,
  },
  {
    id: 'realtime_distance_1000',
    name: '一千米跨越',
    description: '单局飞行中实时距离达到 1000 米',
    icon: '🚀',
    category: 'distance',
    rarity: 'rare',
    condition: { type: 'current_distance_realtime', target: 1000 },
    rewardCoins: 200,
    maxProgress: 1000,
  },
  {
    id: 'realtime_distance_3000',
    name: '三千米远航',
    description: '单局飞行中实时距离达到 3000 米',
    icon: '☄️',
    category: 'distance',
    rarity: 'epic',
    condition: { type: 'current_distance_realtime', target: 3000 },
    rewardCoins: 600,
    maxProgress: 3000,
  },
  {
    id: 'realtime_combo_10',
    name: '十连击新星',
    description: '单局中达到 10 连击',
    icon: '⚡',
    category: 'skill',
    rarity: 'common',
    condition: { type: 'max_combo_realtime', target: 10 },
    rewardCoins: 80,
    maxProgress: 10,
  },
  {
    id: 'realtime_combo_25',
    name: '二十五连击高手',
    description: '单局中达到 25 连击',
    icon: '🔥',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'max_combo_realtime', target: 25 },
    rewardCoins: 250,
    maxProgress: 25,
  },
  {
    id: 'realtime_combo_50',
    name: '五十连击大师',
    description: '单局中达到 50 连击',
    icon: '💫',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'max_combo_realtime', target: 50 },
    rewardCoins: 800,
    maxProgress: 50,
  },
  {
    id: 'realtime_combo_100',
    name: '百连击传说',
    description: '单局中达到 100 连击',
    icon: '👑',
    category: 'skill',
    rarity: 'legendary',
    condition: { type: 'max_combo_realtime', target: 100 },
    rewardCoins: 2500,
    maxProgress: 100,
  },
  {
    id: 'single_aircurrent_20',
    name: '气流收集者',
    description: '单局捕获 20 个上升气流',
    icon: '🌀',
    category: 'skill',
    rarity: 'common',
    condition: { type: 'aircurrent_single', target: 20 },
    rewardCoins: 100,
    maxProgress: 20,
  },
  {
    id: 'single_aircurrent_50',
    name: '气流探险家',
    description: '单局捕获 50 个上升气流',
    icon: '🌪️',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'aircurrent_single', target: 50 },
    rewardCoins: 300,
    maxProgress: 50,
  },
  {
    id: 'single_aircurrent_100',
    name: '气流征服者',
    description: '单局捕获 100 个上升气流',
    icon: '🌬️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'aircurrent_single', target: 100 },
    rewardCoins: 800,
    maxProgress: 100,
  },
  {
    id: 'lightning_survivor_5',
    name: '雷电幸存者',
    description: '累计 5 次与闪电擦边而过',
    icon: '⚡',
    category: 'special',
    rarity: 'rare',
    condition: { type: 'lightning_miss_total', target: 5 },
    rewardCoins: 200,
    maxProgress: 5,
  },
  {
    id: 'lightning_survivor_20',
    name: '雷霆驾驭者',
    description: '累计 20 次与闪电擦边而过',
    icon: '⛈️',
    category: 'special',
    rarity: 'epic',
    condition: { type: 'lightning_miss_total', target: 20 },
    rewardCoins: 600,
    maxProgress: 20,
  },
  {
    id: 'obstacle_dodger_50',
    name: '障碍闪避者',
    description: '累计避开 50 个障碍物',
    icon: '🎯',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'obstacle_avoid_total', target: 50 },
    rewardCoins: 200,
    maxProgress: 50,
  },
  {
    id: 'obstacle_dodger_200',
    name: '幻影穿行',
    description: '累计避开 200 个障碍物',
    icon: '👻',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'obstacle_avoid_total', target: 200 },
    rewardCoins: 600,
    maxProgress: 200,
  },
];

export function createAchievements(): Achievement[] {
  return ACHIEVEMENT_DEFS.map((def) => ({
    ...def,
    unlocked: false,
    unlockedAt: null,
    progress: 0,
  }));
}

const TITLE_DEFS: Array<Omit<Title, 'unlocked' | 'unlockedAt' | 'isEquipped'>> = [
  {
    id: 'title_rookie',
    name: '风筝新手',
    description: '初入天空的新手飞行员',
    icon: '🪁',
    type: 'level',
    rarity: 'common',
    condition: { type: 'min_level', target: 1 },
  },
  {
    id: 'title_apprentice',
    name: '学徒飞行员',
    description: '掌握基础飞行技巧的飞行员',
    icon: '🎓',
    type: 'level',
    rarity: 'common',
    condition: { type: 'min_level', target: 5 },
  },
  {
    id: 'title_skilled',
    name: '熟练飞行员',
    description: '能够熟练操控风筝的飞行员',
    icon: '✨',
    type: 'level',
    rarity: 'common',
    condition: { type: 'min_level', target: 10 },
  },
  {
    id: 'title_senior',
    name: '资深飞行员',
    description: '经验丰富的资深飞行员',
    icon: '🎖️',
    type: 'level',
    rarity: 'rare',
    condition: { type: 'min_level', target: 20 },
  },
  {
    id: 'title_expert',
    name: '飞行专家',
    description: '对飞行有深入研究的专家',
    icon: '🏆',
    type: 'level',
    rarity: 'rare',
    condition: { type: 'min_level', target: 35 },
  },
  {
    id: 'title_master',
    name: '天空大师',
    description: '翱翔天空的大师级飞行员',
    icon: '👑',
    type: 'level',
    rarity: 'epic',
    condition: { type: 'min_level', target: 50 },
  },
  {
    id: 'title_wind_rider',
    name: '风云驾驭者',
    description: '能够驾驭各种天气的强者',
    icon: '🌪️',
    type: 'level',
    rarity: 'epic',
    condition: { type: 'min_level', target: 75 },
  },
  {
    id: 'title_legend',
    name: '传奇飞行家',
    description: '传说中的顶级飞行家',
    icon: '🌟',
    type: 'level',
    rarity: 'legendary',
    condition: { type: 'min_level', target: 100 },
  },
  {
    id: 'title_achievement_collector_10',
    name: '成就收藏家',
    description: '解锁 10 个成就',
    icon: '📚',
    type: 'achievement',
    rarity: 'common',
    condition: { type: 'achievement_count', target: 10 },
  },
  {
    id: 'title_achievement_collector_25',
    name: '成就猎人',
    description: '解锁 25 个成就',
    icon: '🎯',
    type: 'achievement',
    rarity: 'rare',
    condition: { type: 'achievement_count', target: 25 },
  },
  {
    id: 'title_achievement_collector_40',
    name: '成就大师',
    description: '解锁 40 个成就',
    icon: '🏅',
    type: 'achievement',
    rarity: 'epic',
    condition: { type: 'achievement_count', target: 40 },
  },
  {
    id: 'title_score_10k',
    name: '万分选手',
    description: '累计总得分达到 10000 分',
    icon: '💎',
    type: 'score',
    rarity: 'common',
    condition: { type: 'total_score', target: 10000 },
  },
  {
    id: 'title_score_50k',
    name: '五万分精英',
    description: '累计总得分达到 50000 分',
    icon: '💯',
    type: 'score',
    rarity: 'rare',
    condition: { type: 'total_score', target: 50000 },
  },
  {
    id: 'title_score_200k',
    name: '二十万分传奇',
    description: '累计总得分达到 200000 分',
    icon: '🏆',
    type: 'score',
    rarity: 'epic',
    condition: { type: 'total_score', target: 200000 },
  },
  {
    id: 'title_score_500k',
    name: '五十万分神话',
    description: '累计总得分达到 500000 分',
    icon: '👑',
    type: 'score',
    rarity: 'legendary',
    condition: { type: 'total_score', target: 500000 },
  },
  {
    id: 'title_height_200',
    name: '低空探索者',
    description: '最高飞行高度达到 200 米',
    icon: '🏔️',
    type: 'height',
    rarity: 'common',
    condition: { type: 'max_height', target: 200 },
  },
  {
    id: 'title_height_400',
    name: '高空征服者',
    description: '最高飞行高度达到 400 米',
    icon: '☁️',
    type: 'height',
    rarity: 'rare',
    condition: { type: 'max_height', target: 400 },
  },
  {
    id: 'title_height_600',
    name: '云端漫步者',
    description: '最高飞行高度达到 600 米',
    icon: '🌌',
    type: 'height',
    rarity: 'epic',
    condition: { type: 'max_height', target: 600 },
  },
  {
    id: 'title_height_800',
    name: '近空飞行者',
    description: '最高飞行高度达到 800 米',
    icon: '🛰️',
    type: 'height',
    rarity: 'legendary',
    condition: { type: 'max_height', target: 800 },
  },
  {
    id: 'title_distance_10k',
    name: '短途旅人',
    description: '累计飞行距离达到 10000 米',
    icon: '🛤️',
    type: 'distance',
    rarity: 'common',
    condition: { type: 'total_distance', target: 10000 },
  },
  {
    id: 'title_distance_50k',
    name: '中-distance航行家',
    description: '累计飞行距离达到 50000 米',
    icon: '🌉',
    type: 'distance',
    rarity: 'rare',
    condition: { type: 'total_distance', target: 50000 },
  },
  {
    id: 'title_distance_200k',
    name: '长途跋涉者',
    description: '累计飞行距离达到 200000 米',
    icon: '🏔️',
    type: 'distance',
    rarity: 'epic',
    condition: { type: 'total_distance', target: 200000 },
  },
  {
    id: 'title_distance_500k',
    name: '环球旅行家',
    description: '累计飞行距离达到 500000 米',
    icon: '🌍',
    type: 'distance',
    rarity: 'legendary',
    condition: { type: 'total_distance', target: 500000 },
  },
  {
    id: 'title_perfect_10',
    name: '完美飞行者',
    description: '完成 10 次零碰撞飞行',
    icon: '✨',
    type: 'skill',
    rarity: 'common',
    condition: { type: 'perfect_flights', target: 10 },
  },
  {
    id: 'title_perfect_30',
    name: '无瑕飞行员',
    description: '完成 30 次零碰撞飞行',
    icon: '💫',
    type: 'skill',
    rarity: 'rare',
    condition: { type: 'perfect_flights', target: 30 },
  },
  {
    id: 'title_perfect_50',
    name: '精准操控师',
    description: '完成 50 次零碰撞飞行',
    icon: '🎯',
    type: 'skill',
    rarity: 'epic',
    condition: { type: 'perfect_flights', target: 50 },
  },
  {
    id: 'title_streak_10',
    name: '连胜新手',
    description: '连续完成 10 次零碰撞飞行',
    icon: '🔥',
    type: 'skill',
    rarity: 'rare',
    condition: { type: 'consecutive_streak', target: 10 },
  },
  {
    id: 'title_streak_25',
    name: '连胜达人',
    description: '连续完成 25 次零碰撞飞行',
    icon: '☀️',
    type: 'skill',
    rarity: 'epic',
    condition: { type: 'consecutive_streak', target: 25 },
  },
  {
    id: 'title_combo_30',
    name: '连击新星',
    description: '单局最高连击达到 30',
    icon: '⚡',
    type: 'skill',
    rarity: 'common',
    condition: { type: 'max_combo', target: 30 },
  },
  {
    id: 'title_combo_60',
    name: '连击高手',
    description: '单局最高连击达到 60',
    icon: '🔥',
    type: 'skill',
    rarity: 'rare',
    condition: { type: 'max_combo', target: 60 },
  },
  {
    id: 'title_combo_100',
    name: '连击之神',
    description: '单局最高连击达到 100',
    icon: '💥',
    type: 'skill',
    rarity: 'epic',
    condition: { type: 'max_combo', target: 100 },
  },
  {
    id: 'title_legendary_pilot',
    name: '传说飞行员',
    description: '解锁传奇飞行家成就',
    icon: '👑',
    type: 'special',
    rarity: 'legendary',
    condition: { type: 'specific_achievement', target: 1, achievementIds: ['legendary_pilot'] },
  },
  {
    id: 'title_sky_explorer',
    name: '天空探索者',
    description: '解锁全部高度成就',
    icon: '✨',
    type: 'special',
    rarity: 'epic',
    condition: { 
      type: 'achievement_ids', 
      target: 4, 
      achievementIds: ['sky_explorer', 'cloud_dancer', 'strato_boundary', 'near_space'] 
    },
  },
  {
    id: 'title_score_master',
    name: '得分大师',
    description: '解锁全部得分成就',
    icon: '🏆',
    type: 'special',
    rarity: 'epic',
    condition: { 
      type: 'achievement_ids', 
      target: 4, 
      achievementIds: ['score_1000', 'score_5000', 'score_15000', 'score_50000'] 
    },
  },
];

export function createTitles(): Title[] {
  return TITLE_DEFS.map((def) => ({
    ...def,
    unlocked: false,
    unlockedAt: null,
    isEquipped: false,
  }));
}

export function createDefaultProfile(): PilotProfile {
  return {
    name: '未命名飞行员',
    title: '风筝新手',
    level: 1,
    experience: 0,
    experienceToNext: 100,
    joinDate: Date.now(),
    totalFlights: 0,
    totalFlightTime: 0,
    totalDistance: 0,
    totalScore: 0,
    totalAirCurrents: 0,
    totalCollisions: 0,
    perfectFlights: 0,
    currentStreak: 0,
    bestStreak: 0,
    favoriteMode: 'free',
  };
}

export function createDefaultJourneyState(): JourneyState {
  return {
    profile: createDefaultProfile(),
    flightRecords: [],
    achievements: createAchievements(),
    titles: createTitles(),
    bestTrajectories: [],
    anomalies: [],
    growthHistory: [],
    recentWeatherTypes: [],
  };
}

export function experienceForLevel(level: number): number {
  return Math.floor(100 * Math.pow(1.25, level - 1));
}
