import type { Achievement, PilotProfile, JourneyState } from './types';

const ACHIEVEMENT_DEFS: Array<Omit<Achievement, 'unlocked' | 'unlockedAt' | 'progress'>> = [
  {
    id: 'first_flight',
    name: '初次起飞',
    description: '完成第一次风筝飞行',
    icon: '🪁',
    category: 'special',
    rarity: 'common',
    condition: { type: 'total_flights', target: 1 },
    rewardCoins: 50,
    maxProgress: 1,
  },
  {
    id: 'rookie_pilot',
    name: '菜鸟飞行员',
    description: '累计完成 10 次飞行',
    icon: '🎯',
    category: 'special',
    rarity: 'common',
    condition: { type: 'total_flights', target: 10 },
    rewardCoins: 100,
    maxProgress: 10,
  },
  {
    id: 'veteran_pilot',
    name: '资深飞行员',
    description: '累计完成 100 次飞行',
    icon: '🏅',
    category: 'special',
    rarity: 'rare',
    condition: { type: 'total_flights', target: 100 },
    rewardCoins: 500,
    maxProgress: 100,
  },
  {
    id: 'legendary_pilot',
    name: '传奇飞行家',
    description: '累计完成 500 次飞行',
    icon: '👑',
    category: 'special',
    rarity: 'legendary',
    condition: { type: 'total_flights', target: 500 },
    rewardCoins: 2000,
    maxProgress: 500,
  },
  {
    id: 'short_journey',
    name: '短途旅行',
    description: '累计飞行距离达到 1000 米',
    icon: '🛤️',
    category: 'distance',
    rarity: 'common',
    condition: { type: 'total_distance', target: 1000 },
    rewardCoins: 80,
    maxProgress: 1000,
  },
  {
    id: 'medium_journey',
    name: '中距离航行',
    description: '累计飞行距离达到 10000 米',
    icon: '🌉',
    category: 'distance',
    rarity: 'rare',
    condition: { type: 'total_distance', target: 10000 },
    rewardCoins: 300,
    maxProgress: 10000,
  },
  {
    id: 'long_journey',
    name: '长途跋涉',
    description: '累计飞行距离达到 50000 米',
    icon: '🏔️',
    category: 'distance',
    rarity: 'epic',
    condition: { type: 'total_distance', target: 50000 },
    rewardCoins: 800,
    maxProgress: 50000,
  },
  {
    id: 'ultra_journey',
    name: '环球飞行',
    description: '累计飞行距离达到 200000 米',
    icon: '🌍',
    category: 'distance',
    rarity: 'legendary',
    condition: { type: 'total_distance', target: 200000 },
    rewardCoins: 3000,
    maxProgress: 200000,
  },
  {
    id: 'single_distance_500',
    name: '五百米冲刺',
    description: '单次飞行距离达到 500 米',
    icon: '💨',
    category: 'distance',
    rarity: 'common',
    condition: { type: 'max_distance_single', target: 500 },
    rewardCoins: 60,
    maxProgress: 500,
  },
  {
    id: 'single_distance_2000',
    name: '两千米跨越',
    description: '单次飞行距离达到 2000 米',
    icon: '🚀',
    category: 'distance',
    rarity: 'rare',
    condition: { type: 'max_distance_single', target: 2000 },
    rewardCoins: 250,
    maxProgress: 2000,
  },
  {
    id: 'single_distance_5000',
    name: '五千米奇迹',
    description: '单次飞行距离达到 5000 米',
    icon: '☄️',
    category: 'distance',
    rarity: 'epic',
    condition: { type: 'max_distance_single', target: 5000 },
    rewardCoins: 1000,
    maxProgress: 5000,
  },
  {
    id: 'sky_explorer',
    name: '天空探索者',
    description: '达到 200 米的高度',
    icon: '🏔️',
    category: 'height',
    rarity: 'common',
    condition: { type: 'max_height', target: 200 },
    rewardCoins: 80,
    maxProgress: 200,
  },
  {
    id: 'cloud_dancer',
    name: '云端舞者',
    description: '达到 350 米的高度',
    icon: '☁️',
    category: 'height',
    rarity: 'rare',
    condition: { type: 'max_height', target: 350 },
    rewardCoins: 300,
    maxProgress: 350,
  },
  {
    id: 'strato_boundary',
    name: '平流层边界',
    description: '达到 500 米的高度',
    icon: '🌌',
    category: 'height',
    rarity: 'epic',
    condition: { type: 'max_height', target: 500 },
    rewardCoins: 800,
    maxProgress: 500,
  },
  {
    id: 'near_space',
    name: '近空飞行',
    description: '达到 800 米的高度',
    icon: '🛰️',
    category: 'height',
    rarity: 'legendary',
    condition: { type: 'max_height', target: 800 },
    rewardCoins: 2500,
    maxProgress: 800,
  },
  {
    id: 'score_1000',
    name: '千分达成',
    description: '单次飞行得分达到 1000 分',
    icon: '💯',
    category: 'score',
    rarity: 'common',
    condition: { type: 'max_score_single', target: 1000 },
    rewardCoins: 60,
    maxProgress: 1000,
  },
  {
    id: 'score_5000',
    name: '五千分能手',
    description: '单次飞行得分达到 5000 分',
    icon: '🎖️',
    category: 'score',
    rarity: 'rare',
    condition: { type: 'max_score_single', target: 5000 },
    rewardCoins: 250,
    maxProgress: 5000,
  },
  {
    id: 'score_15000',
    name: '一万五千分大师',
    description: '单次飞行得分达到 15000 分',
    icon: '🏆',
    category: 'score',
    rarity: 'epic',
    condition: { type: 'max_score_single', target: 15000 },
    rewardCoins: 800,
    maxProgress: 15000,
  },
  {
    id: 'score_50000',
    name: '五万分传奇',
    description: '单次飞行得分达到 50000 分',
    icon: '🌟',
    category: 'score',
    rarity: 'legendary',
    condition: { type: 'max_score_single', target: 50000 },
    rewardCoins: 3000,
    maxProgress: 50000,
  },
  {
    id: 'total_score_10000',
    name: '万分积累',
    description: '累计总得分达到 10000 分',
    icon: '📊',
    category: 'score',
    rarity: 'common',
    condition: { type: 'total_score', target: 10000 },
    rewardCoins: 100,
    maxProgress: 10000,
  },
  {
    id: 'total_score_100000',
    name: '十万分俱乐部',
    description: '累计总得分达到 100000 分',
    icon: '💎',
    category: 'score',
    rarity: 'epic',
    condition: { type: 'total_score', target: 100000 },
    rewardCoins: 1000,
    maxProgress: 100000,
  },
  {
    id: 'aircurrent_hunter_10',
    name: '气流猎人',
    description: '累计捕获 10 个上升气流',
    icon: '🌀',
    category: 'skill',
    rarity: 'common',
    condition: { type: 'aircurrent_total', target: 10 },
    rewardCoins: 50,
    maxProgress: 10,
  },
  {
    id: 'aircurrent_hunter_100',
    name: '气流大师',
    description: '累计捕获 100 个上升气流',
    icon: '🌪️',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'aircurrent_total', target: 100 },
    rewardCoins: 250,
    maxProgress: 100,
  },
  {
    id: 'aircurrent_hunter_500',
    name: '气流传奇',
    description: '累计捕获 500 个上升气流',
    icon: '🌬️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'aircurrent_total', target: 500 },
    rewardCoins: 800,
    maxProgress: 500,
  },
  {
    id: 'perfect_5',
    name: '无瑕飞行',
    description: '完成 5 次零碰撞飞行',
    icon: '✨',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'perfect_flights', target: 5 },
    rewardCoins: 200,
    maxProgress: 5,
  },
  {
    id: 'perfect_20',
    name: '精准大师',
    description: '完成 20 次零碰撞飞行',
    icon: '💫',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'perfect_flights', target: 20 },
    rewardCoins: 600,
    maxProgress: 20,
  },
  {
    id: 'streak_5',
    name: '连胜五次',
    description: '连续完成 5 次零碰撞飞行',
    icon: '🔥',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'consecutive_no_collision', target: 5 },
    rewardCoins: 250,
    maxProgress: 5,
  },
  {
    id: 'streak_15',
    name: '连续完美',
    description: '连续完成 15 次零碰撞飞行',
    icon: '☀️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'consecutive_no_collision', target: 15 },
    rewardCoins: 800,
    maxProgress: 15,
  },
  {
    id: 'all_modes',
    name: '全能飞行员',
    description: '体验全部 5 种飞行模式',
    icon: '🎪',
    category: 'exploration',
    rarity: 'epic',
    condition: { type: 'modes_unlocked', target: 5 },
    rewardCoins: 500,
    maxProgress: 5,
  },
  {
    id: 'weather_adventurer',
    name: '天气冒险家',
    description: '在 4 种不同天气条件下飞行',
    icon: '🌤️',
    category: 'exploration',
    rarity: 'rare',
    condition: { type: 'weather_experienced', target: 4 },
    rewardCoins: 300,
    maxProgress: 4,
  },
  {
    id: 'zero_collision_1000',
    name: '千里无碰撞',
    description: '零碰撞累计飞行 1000 米',
    icon: '🎯',
    category: 'skill',
    rarity: 'rare',
    condition: { type: 'zero_collision_distance', target: 1000 },
    rewardCoins: 300,
    maxProgress: 1000,
  },
  {
    id: 'zero_collision_5000',
    name: '完美远航',
    description: '零碰撞累计飞行 5000 米',
    icon: '🎖️',
    category: 'skill',
    rarity: 'epic',
    condition: { type: 'zero_collision_distance', target: 5000 },
    rewardCoins: 800,
    maxProgress: 5000,
  },
];

export function createAchievements(): Achievement[] {
  return ACHIEVEMENT_DEFS.map((def) => ({
    ...def,
    unlocked: false,
    unlockedAt: null,
    progress: 0,
  }));
}

export function createDefaultProfile(): PilotProfile {
  return {
    name: '未命名飞行员',
    title: '风筝新手',
    level: 1,
    experience: 0,
    experienceToNext: 100,
    joinDate: Date.now(),
    totalFlights: 0,
    totalFlightTime: 0,
    totalDistance: 0,
    totalScore: 0,
    totalAirCurrents: 0,
    totalCollisions: 0,
    perfectFlights: 0,
    currentStreak: 0,
    bestStreak: 0,
    favoriteMode: 'free',
  };
}

export function createDefaultJourneyState(): JourneyState {
  return {
    profile: createDefaultProfile(),
    flightRecords: [],
    achievements: createAchievements(),
    bestTrajectories: [],
    anomalies: [],
    growthHistory: [],
    recentWeatherTypes: [],
  };
}

export function experienceForLevel(level: number): number {
  return Math.floor(100 * Math.pow(1.25, level - 1));
}
