import type { DivisionConfig, TrackConfig, ChapterConfig } from './types';

export const DIVISIONS: DivisionConfig[] = [
  {
    id: 'novice',
    name: '新手组',
    icon: '🌱',
    color: '#4ecdc4',
    minScore: 0,
    maxScore: 1500,
    description: '初入风筝世界的新手，学习基本操控与气流辨识',
  },
  {
    id: 'intermediate',
    name: '进阶组',
    icon: '⚡',
    color: '#3b82f6',
    minScore: 1500,
    maxScore: 3000,
    description: '掌握气流规律，能稳定飞行并追踪影子',
  },
  {
    id: 'advanced',
    name: '高手组',
    icon: '🔥',
    color: '#ff6b6b',
    minScore: 3000,
    maxScore: 6000,
    description: '精准操控风筝，在恶劣天气中仍能保持高分',
  },
  {
    id: 'master',
    name: '大师组',
    icon: '👑',
    color: '#ffd700',
    minScore: 6000,
    maxScore: Infinity,
    description: '传说中的风筝大师，挑战极限赛道',
  },
];

export const TRACKS: TrackConfig[] = [
  {
    id: 'track_01_01',
    chapterId: 'chapter_01',
    name: '春风初试',
    description: '在微风中学习基本的飞行与影子追踪',
    difficulty: 'easy',
    division: 'novice',
    rules: [
      { id: 'gentle_wind', label: '和风', description: '风速较低，适合初学者', modifier: 0.8 },
      { id: 'extra_time', label: '额外时间', description: '时间限制延长50%', modifier: 1.5 },
    ],
    targetScore: 500,
    timeLimit: 120,
    worldSize: 400,
    gravity: 0.012,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.06,
    maxAirCurrentStrength: 0.15,
    minBuildingHeight: 10,
    maxBuildingHeight: 40,
    buildingDensity: 0.2,
    windSpeed: 0.15,
    turbulenceLevel: 0.1,
    cloudCoverage: 0.3,
    checkpointCount: 3,
    coinReward: 50,
    unlockTrackId: 'track_01_02',
  },
  {
    id: 'track_01_02',
    chapterId: 'chapter_01',
    name: '城市穿越',
    description: '穿梭于低矮建筑之间，掌握转向与避障',
    difficulty: 'easy',
    division: 'novice',
    rules: [
      { id: 'dense_buildings', label: '密集建筑', description: '建筑物密度增加', modifier: 1.3 },
      { id: 'air_boost', label: '气流加成', description: '上升气流更频繁', modifier: 1.2 },
    ],
    targetScore: 800,
    timeLimit: 100,
    worldSize: 450,
    gravity: 0.013,
    airCurrentSpawnRate: 0.025,
    minAirCurrentStrength: 0.07,
    maxAirCurrentStrength: 0.16,
    minBuildingHeight: 12,
    maxBuildingHeight: 45,
    buildingDensity: 0.35,
    windSpeed: 0.2,
    turbulenceLevel: 0.15,
    cloudCoverage: 0.35,
    checkpointCount: 4,
    coinReward: 80,
    unlockTrackId: 'track_02_01',
  },
  {
    id: 'track_02_01',
    chapterId: 'chapter_02',
    name: '气流猎人',
    description: '在变化多端的风中捕捉每一个上升气流',
    difficulty: 'normal',
    division: 'intermediate',
    rules: [
      { id: 'variable_wind', label: '多变风场', description: '风速与方向频繁变化', modifier: 1.4 },
      { id: 'combo_bonus', label: '连击奖励', description: '连续捕获气流可获得额外分数', modifier: 1.5 },
    ],
    targetScore: 1500,
    timeLimit: 90,
    worldSize: 500,
    gravity: 0.015,
    airCurrentSpawnRate: 0.02,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 15,
    maxBuildingHeight: 50,
    buildingDensity: 0.3,
    windSpeed: 0.3,
    turbulenceLevel: 0.25,
    cloudCoverage: 0.5,
    checkpointCount: 5,
    coinReward: 120,
    unlockTrackId: 'track_02_02',
  },
  {
    id: 'track_02_02',
    chapterId: 'chapter_02',
    name: '影子追踪者',
    description: '保持高影子追踪度，在光影中找到最佳路径',
    difficulty: 'normal',
    division: 'intermediate',
    rules: [
      { id: 'shadow_focus', label: '影子聚焦', description: '影子追踪分数权重加倍', modifier: 2.0 },
      { id: 'medium_turbulence', label: '中度乱流', description: '乱流更频繁出现', modifier: 1.3 },
    ],
    targetScore: 2000,
    timeLimit: 85,
    worldSize: 520,
    gravity: 0.015,
    airCurrentSpawnRate: 0.018,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 18,
    maxBuildingHeight: 55,
    buildingDensity: 0.3,
    windSpeed: 0.35,
    turbulenceLevel: 0.3,
    cloudCoverage: 0.55,
    checkpointCount: 5,
    coinReward: 150,
    unlockTrackId: 'track_03_01',
  },
  {
    id: 'track_03_01',
    chapterId: 'chapter_03',
    name: '暴风前线',
    description: '在强风与暴雨中飞行，考验你的操控极限',
    difficulty: 'hard',
    division: 'advanced',
    rules: [
      { id: 'storm_wind', label: '暴风', description: '风速极高，需精准操控', modifier: 1.8 },
      { id: 'downdraft_zone', label: '下降气流区', description: '下降气流频繁出现', modifier: 1.5 },
      { id: 'score_surge', label: '得分飙升', description: '所有得分×1.5倍', modifier: 1.5 },
    ],
    targetScore: 3000,
    timeLimit: 80,
    worldSize: 550,
    gravity: 0.018,
    airCurrentSpawnRate: 0.015,
    minAirCurrentStrength: 0.1,
    maxAirCurrentStrength: 0.25,
    minBuildingHeight: 20,
    maxBuildingHeight: 60,
    buildingDensity: 0.35,
    windSpeed: 0.5,
    turbulenceLevel: 0.45,
    cloudCoverage: 0.7,
    checkpointCount: 6,
    coinReward: 250,
    unlockTrackId: 'track_03_02',
  },
  {
    id: 'track_03_02',
    chapterId: 'chapter_03',
    name: '高空翱翔',
    description: '在高海拔区域飞行，空气稀薄但视野开阔',
    difficulty: 'hard',
    division: 'advanced',
    rules: [
      { id: 'thin_air', label: '稀薄空气', description: '升力降低，需要更多气流支撑', modifier: 1.6 },
      { id: 'height_bonus', label: '高度奖励', description: '高度得分权重×2', modifier: 2.0 },
    ],
    targetScore: 4000,
    timeLimit: 75,
    worldSize: 600,
    gravity: 0.02,
    airCurrentSpawnRate: 0.012,
    minAirCurrentStrength: 0.1,
    maxAirCurrentStrength: 0.22,
    minBuildingHeight: 25,
    maxBuildingHeight: 65,
    buildingDensity: 0.25,
    windSpeed: 0.4,
    turbulenceLevel: 0.4,
    cloudCoverage: 0.6,
    checkpointCount: 6,
    coinReward: 300,
    unlockTrackId: 'track_04_01',
  },
  {
    id: 'track_04_01',
    chapterId: 'chapter_04',
    name: '混沌之翼',
    description: '在极端天气中穿越混乱的城市，只有大师才能驾驭',
    difficulty: 'extreme',
    division: 'master',
    rules: [
      { id: 'chaos', label: '混沌', description: '天气系统完全随机', modifier: 2.0 },
      { id: 'no_margin', label: '零容错', description: '碰撞惩罚翻倍', modifier: 2.0 },
      { id: 'triple_score', label: '三倍得分', description: '所有得分×3倍', modifier: 3.0 },
    ],
    targetScore: 6000,
    timeLimit: 70,
    worldSize: 650,
    gravity: 0.022,
    airCurrentSpawnRate: 0.01,
    minAirCurrentStrength: 0.12,
    maxAirCurrentStrength: 0.28,
    minBuildingHeight: 25,
    maxBuildingHeight: 70,
    buildingDensity: 0.4,
    windSpeed: 0.6,
    turbulenceLevel: 0.6,
    cloudCoverage: 0.8,
    checkpointCount: 8,
    coinReward: 500,
    unlockTrackId: 'track_04_02',
  },
  {
    id: 'track_04_02',
    chapterId: 'chapter_04',
    name: '天际传说',
    description: '最终挑战——在传说中的天际线之上翱翔',
    difficulty: 'extreme',
    division: 'master',
    rules: [
      { id: 'legendary', label: '传说', description: '所有参数极限化', modifier: 2.5 },
      { id: 'perfect_only', label: '完美主义', description: '只有完美飞行才能获得高分', modifier: 2.0 },
      { id: 'quad_score', label: '四倍得分', description: '所有得分×4倍', modifier: 4.0 },
    ],
    targetScore: 10000,
    timeLimit: 60,
    worldSize: 700,
    gravity: 0.025,
    airCurrentSpawnRate: 0.008,
    minAirCurrentStrength: 0.14,
    maxAirCurrentStrength: 0.3,
    minBuildingHeight: 30,
    maxBuildingHeight: 80,
    buildingDensity: 0.45,
    windSpeed: 0.7,
    turbulenceLevel: 0.7,
    cloudCoverage: 0.85,
    checkpointCount: 10,
    coinReward: 800,
    unlockTrackId: null,
  },
];

export const CHAPTERS: ChapterConfig[] = [
  {
    id: 'chapter_01',
    name: '初风启程',
    description: '学习风筝操控的基础，在温柔的天空中展翅',
    icon: '🌬️',
    trackIds: ['track_01_01', 'track_01_02'],
    requiredCompletions: 2,
    requiredMasteries: 0,
    unlockChapterId: null,
  },
  {
    id: 'chapter_02',
    name: '追影之旅',
    description: '追寻影子的轨迹，在变幻的风中找到方向',
    icon: '🌤️',
    trackIds: ['track_02_01', 'track_02_02'],
    requiredCompletions: 2,
    requiredMasteries: 1,
    unlockChapterId: 'chapter_01',
  },
  {
    id: 'chapter_03',
    name: '暴风试炼',
    description: '在暴风与乱流中证明你的实力',
    icon: '⛈️',
    trackIds: ['track_03_01', 'track_03_02'],
    requiredCompletions: 2,
    requiredMasteries: 1,
    unlockChapterId: 'chapter_02',
  },
  {
    id: 'chapter_04',
    name: '天际传说',
    description: '传说级赛道，只有真正的风筝大师才能征服',
    icon: '🏆',
    trackIds: ['track_04_01', 'track_04_02'],
    requiredCompletions: 2,
    requiredMasteries: 2,
    unlockChapterId: 'chapter_03',
  },
];

export const NPC_LEADERBOARD = [
  { name: '风筝少年·小明', division: 'novice' as const, baseScore: 620 },
  { name: '御风者·小红', division: 'novice' as const, baseScore: 780 },
  { name: '追影人·阿杰', division: 'intermediate' as const, baseScore: 1650 },
  { name: '破风者·晓晨', division: 'intermediate' as const, baseScore: 2100 },
  { name: '风暴骑手·阿风', division: 'intermediate' as const, baseScore: 2500 },
  { name: '翱翔者·天翼', division: 'advanced' as const, baseScore: 3400 },
  { name: '云端行者·凌霄', division: 'advanced' as const, baseScore: 4200 },
  { name: '天空之主·苍穹', division: 'advanced' as const, baseScore: 5100 },
  { name: '传说风筝师·御天', division: 'master' as const, baseScore: 6500 },
  { name: '天际之风·破晓', division: 'master' as const, baseScore: 8800 },
  { name: '永恒之风·星穹', division: 'master' as const, baseScore: 11500 },
];
