import type { WeatherScene } from './types';
import { DEFAULT_WIND_FIELD } from './types';
import { DEFAULT_WEATHER, DEFAULT_GAME_CONFIG } from '../game/types';

export const PRESET_SCENES: WeatherScene[] = [
  {
    id: 'scene_calm_morning',
    name: '宁静清晨',
    description: '微风轻拂，适合新手练习基础操控技巧',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: true,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.15,
      windDirection: { x: 1, y: 0, z: 0.2 },
      cloudCoverage: 0.2,
      timeOfDay: 0.25,
      turbulenceLevel: 0.1,
    },
    gameConfig: {
      worldSize: 500,
      gravity: 0.015,
      airCurrentSpawnRate: 0.015,
      minAirCurrentStrength: 0.06,
      maxAirCurrentStrength: 0.12,
      minBuildingHeight: 15,
      maxBuildingHeight: 50,
      buildingDensity: 0.25,
      turbulenceLevel: 0.1,
      cloudCoverage: 0.2,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.15,
      turbulenceLevel: 0.1,
      gustStrength: 0.05,
      gustFrequency: 0.02,
    },
    icon: '🌅',
    difficulty: 'easy',
    tags: ['新手友好', '低风速', '稳定', '日出'],
  },
  {
    id: 'scene_breezy_afternoon',
    name: '午后微风',
    description: '适中的风力，适合进阶飞行技巧训练',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: true,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.4,
      windDirection: { x: 0.8, y: 0, z: 0.5 },
      cloudCoverage: 0.5,
      timeOfDay: 0.5,
      turbulenceLevel: 0.25,
    },
    gameConfig: {
      worldSize: 500,
      gravity: 0.015,
      airCurrentSpawnRate: 0.025,
      minAirCurrentStrength: 0.08,
      maxAirCurrentStrength: 0.18,
      minBuildingHeight: 15,
      maxBuildingHeight: 60,
      buildingDensity: 0.3,
      turbulenceLevel: 0.25,
      cloudCoverage: 0.5,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.4,
      turbulenceLevel: 0.25,
      gustStrength: 0.12,
      gustFrequency: 0.06,
    },
    icon: '☀️',
    difficulty: 'medium',
    tags: ['标准', '中速风', '晴间多云', '暖气流'],
  },
  {
    id: 'scene_windy_challenge',
    name: '疾风挑战',
    description: '强风环境，考验风筝的稳定性和操控技巧',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.7,
      windDirection: { x: 0.9, y: 0, z: -0.4 },
      cloudCoverage: 0.7,
      timeOfDay: 0.4,
      turbulenceLevel: 0.5,
    },
    gameConfig: {
      worldSize: 600,
      gravity: 0.018,
      airCurrentSpawnRate: 0.035,
      minAirCurrentStrength: 0.12,
      maxAirCurrentStrength: 0.25,
      minBuildingHeight: 20,
      maxBuildingHeight: 70,
      buildingDensity: 0.35,
      turbulenceLevel: 0.5,
      cloudCoverage: 0.7,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.7,
      turbulenceLevel: 0.5,
      gustStrength: 0.25,
      gustFrequency: 0.1,
      shearFactor: 0.04,
    },
    icon: '💨',
    difficulty: 'hard',
    tags: ['强风', '挑战', '多云', '高湍流'],
  },
  {
    id: 'scene_stormy_night',
    name: '风暴之夜',
    description: '极端天气，只有顶级风筝大师才能驾驭',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 1.2,
      windDirection: { x: -0.5, y: 0, z: -0.8 },
      cloudCoverage: 0.95,
      timeOfDay: 0.9,
      turbulenceLevel: 0.8,
    },
    gameConfig: {
      worldSize: 700,
      gravity: 0.022,
      airCurrentSpawnRate: 0.05,
      minAirCurrentStrength: 0.18,
      maxAirCurrentStrength: 0.35,
      minBuildingHeight: 25,
      maxBuildingHeight: 80,
      buildingDensity: 0.4,
      turbulenceLevel: 0.8,
      cloudCoverage: 0.95,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 1.2,
      turbulenceLevel: 0.8,
      gustStrength: 0.4,
      gustFrequency: 0.15,
      shearFactor: 0.06,
    },
    icon: '⛈️',
    difficulty: 'extreme',
    tags: ['风暴', '极端', '夜间', '极限挑战'],
  },
  {
    id: 'scene_thermal_soaring',
    name: '热气流翱翔',
    description: '大量上升气流，适合追求高度和距离',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: true,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.35,
      windDirection: { x: 0.7, y: 0, z: 0.7 },
      cloudCoverage: 0.3,
      timeOfDay: 0.3,
      turbulenceLevel: 0.3,
    },
    gameConfig: {
      worldSize: 600,
      gravity: 0.013,
      airCurrentSpawnRate: 0.04,
      minAirCurrentStrength: 0.15,
      maxAirCurrentStrength: 0.3,
      minBuildingHeight: 15,
      maxBuildingHeight: 55,
      buildingDensity: 0.25,
      turbulenceLevel: 0.3,
      cloudCoverage: 0.3,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.35,
      turbulenceLevel: 0.3,
      gustStrength: 0.08,
      gustFrequency: 0.04,
      boundaryLayerHeight: 80,
    },
    icon: '🦅',
    difficulty: 'medium',
    tags: ['热气流', '高飞', '晴朗', '长距离'],
  },
  {
    id: 'scene_turbulence_training',
    name: '湍流训练场',
    description: '专门用于研究和适应湍流环境',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.5,
      windDirection: { x: 1, y: 0, z: 0 },
      cloudCoverage: 0.6,
      timeOfDay: 0.6,
      turbulenceLevel: 0.7,
    },
    gameConfig: {
      worldSize: 500,
      gravity: 0.016,
      airCurrentSpawnRate: 0.045,
      minAirCurrentStrength: 0.1,
      maxAirCurrentStrength: 0.28,
      minBuildingHeight: 18,
      maxBuildingHeight: 65,
      buildingDensity: 0.35,
      turbulenceLevel: 0.7,
      cloudCoverage: 0.6,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.5,
      turbulenceLevel: 0.7,
      gustStrength: 0.3,
      gustFrequency: 0.12,
      shearFactor: 0.05,
    },
    icon: '🌀',
    difficulty: 'hard',
    tags: ['湍流', '训练', '研究', '高难度'],
  },
  {
    id: 'scene_dusk_serenity',
    name: '黄昏静谧',
    description: '柔和的光线和稳定的气流，优美的飞行体验',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.25,
      windDirection: { x: 0.6, y: 0, z: 0.8 },
      cloudCoverage: 0.4,
      timeOfDay: 0.85,
      turbulenceLevel: 0.15,
    },
    gameConfig: {
      ...DEFAULT_GAME_CONFIG,
      worldSize: 550,
      airCurrentSpawnRate: 0.02,
      minAirCurrentStrength: 0.07,
      maxAirCurrentStrength: 0.15,
      buildingDensity: 0.28,
      turbulenceLevel: 0.15,
      cloudCoverage: 0.4,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.25,
      turbulenceLevel: 0.15,
      gustStrength: 0.06,
      gustFrequency: 0.03,
    },
    icon: '🌆',
    difficulty: 'easy',
    tags: ['黄昏', '优美', '轻松', '观赏'],
  },
  {
    id: 'scene_mountain_winds',
    name: '山谷风',
    description: '模拟山谷中的复杂气流模式',
    category: 'preset',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isFavorite: false,
    weatherConfig: {
      ...DEFAULT_WEATHER,
      windSpeed: 0.55,
      windDirection: { x: 0.4, y: 0, z: 0.9 },
      cloudCoverage: 0.55,
      timeOfDay: 0.45,
      turbulenceLevel: 0.45,
    },
    gameConfig: {
      worldSize: 650,
      gravity: 0.017,
      airCurrentSpawnRate: 0.03,
      minAirCurrentStrength: 0.1,
      maxAirCurrentStrength: 0.22,
      minBuildingHeight: 30,
      maxBuildingHeight: 100,
      buildingDensity: 0.45,
      turbulenceLevel: 0.45,
      cloudCoverage: 0.55,
    },
    windField: {
      ...DEFAULT_WIND_FIELD,
      windSpeed: 0.55,
      turbulenceLevel: 0.45,
      gustStrength: 0.18,
      gustFrequency: 0.08,
      shearFactor: 0.035,
      boundaryLayerHeight: 120,
    },
    icon: '🏔️',
    difficulty: 'hard',
    tags: ['山谷', '复杂气流', '高楼', '多变'],
  },
];

export const INITIAL_RECORDS: string[] = [];
