import type { Stage, StageTask, TaskDifficulty, Chapter } from './types';

const createTask = (
  id: string,
  name: string,
  description: string,
  type: StageTask['type'],
  targetValue: number,
  difficulty: TaskDifficulty,
  rewardScore: number,
  rewardCoins: number,
  timeLimit?: number
): StageTask => ({
  id,
  name,
  description,
  type,
  targetValue,
  currentValue: 0,
  difficulty,
  rewardScore,
  rewardCoins,
  completed: false,
  progress: 0,
  timeLimit,
});

export const CHAPTERS: Chapter[] = [
  {
    id: 'chapter-1',
    name: '云端启程',
    subtitle: '初识天空',
    description: '从零开始，学习风筝飞行的基础技巧。在晴朗的天空下感受风的韵律。',
    chapterNumber: 1,
    stageIds: ['stage-1', 'stage-2'],
    unlockCondition: { type: 'always' },
    unlocked: true,
    completed: false,
    totalStars: 0,
    maxStars: 6,
    unlockedDifficulties: ['easy', 'normal'],
    themeColor: '#4ecdc4',
    themeGradient: 'linear-gradient(135deg, #4ecdc4, #44a08d)',
    icon: '🌤️',
  },
  {
    id: 'chapter-2',
    name: '风之试炼',
    subtitle: '驾驭狂风',
    description: '风暴来袭，真正的考验开始了。在剧烈的气流中证明你的飞行实力。',
    chapterNumber: 2,
    stageIds: ['stage-3'],
    unlockCondition: { type: 'chapter_complete', chapterId: 'chapter-1', minStars: 4 },
    unlocked: false,
    completed: false,
    totalStars: 0,
    maxStars: 3,
    unlockedDifficulties: ['easy', 'normal', 'hard'],
    themeColor: '#667eea',
    themeGradient: 'linear-gradient(135deg, #667eea, #764ba2)',
    icon: '🌬️',
  },
  {
    id: 'chapter-3',
    name: '暗夜征途',
    subtitle: '月下翱翔',
    description: '夜幕降临，星辰指引方向。在黑暗中磨砺你的直觉与技巧。',
    chapterNumber: 3,
    stageIds: ['stage-4'],
    unlockCondition: { type: 'chapter_complete', chapterId: 'chapter-2', minStars: 2 },
    unlocked: false,
    completed: false,
    totalStars: 0,
    maxStars: 3,
    unlockedDifficulties: ['easy', 'normal', 'hard'],
    themeColor: '#6366f1',
    themeGradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    icon: '🌙',
  },
  {
    id: 'chapter-4',
    name: '传说纪元',
    subtitle: '至高荣耀',
    description: '传说之巅，雷电交加。唯有最顶尖的风筝大师才能抵达此处。',
    chapterNumber: 4,
    stageIds: ['stage-5'],
    unlockCondition: { type: 'total_stars', count: 8 },
    unlocked: false,
    completed: false,
    totalStars: 0,
    maxStars: 3,
    unlockedDifficulties: ['easy', 'normal', 'hard', 'extreme'],
    themeColor: '#f59e0b',
    themeGradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    icon: '⚡',
  },
];

export const STAGES: Stage[] = [
  {
    id: 'stage-1',
    name: '初入云际',
    description: '新手训练赛段，掌握基本飞行技巧',
    stageNumber: 1,
    chapterId: 'chapter-1',
    tasks: [
      createTask('s1-t1', '起步飞行', '飞行距离达到 500 米', 'distanceTarget', 500, 'easy', 200, 10),
      createTask('s1-t2', '爬升挑战', '达到 100 米高度', 'heightTarget', 100, 'easy', 300, 15),
      createTask('s1-t3', '初次相遇', '捕获 10 个气流', 'airCurrentCount', 10, 'easy', 250, 12),
    ],
    weatherTheme: 'sunny',
    airCurrentTheme: 'calm',
    backgroundStory: '阳光明媚的一天，适合初学者练习风筝飞行。轻柔的海风迎面吹来，天空中飘着几朵白云。',
    totalRewardScore: 750,
    totalRewardCoins: 37,
    unlocked: true,
    completed: false,
    stars: 0,
    bestScore: 0,
  },
  {
    id: 'stage-2',
    name: '追风少年',
    description: '中级赛段，学习利用气流',
    stageNumber: 2,
    chapterId: 'chapter-1',
    tasks: [
      createTask('s2-t1', '远走高飞', '飞行距离达到 1500 米', 'distanceTarget', 1500, 'medium', 500, 25),
      createTask('s2-t2', '云层之上', '达到 180 米高度', 'heightTarget', 180, 'medium', 600, 30),
      createTask('s2-t3', '气流猎手', '捕获 30 个气流', 'airCurrentCount', 30, 'medium', 550, 28),
      createTask('s2-t4', '影子舞者', '保持影子追踪度 60% 以上持续 30 秒', 'shadowTracking', 0.6, 'medium', 400, 20),
    ],
    weatherTheme: 'cloudy',
    airCurrentTheme: 'moderate',
    backgroundStory: '多云天气，气流变得更加活跃。学习在云层间穿梭，捕捉每一股上升气流。',
    totalRewardScore: 2050,
    totalRewardCoins: 103,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
  },
  {
    id: 'stage-3',
    name: '风暴追逐者',
    description: '高级赛段，挑战狂风骤雨',
    stageNumber: 3,
    chapterId: 'chapter-2',
    tasks: [
      createTask('s3-t1', '疾风飞行', '飞行距离达到 3000 米', 'distanceTarget', 3000, 'hard', 1000, 50),
      createTask('s3-t2', '冲上云霄', '达到 250 米高度', 'heightTarget', 250, 'hard', 1200, 60),
      createTask('s3-t3', '风暴之心', '捕获 60 个气流', 'airCurrentCount', 60, 'hard', 1100, 55),
      createTask('s3-t4', '稳如磐石', '保持飞行稳定性 75% 以上持续 60 秒', 'stabilityMaintain', 0.75, 'hard', 800, 40),
      createTask('s3-t5', '连击大师', '连续捕获 15 个气流不中断', 'comboAirCurrent', 15, 'hard', 900, 45),
    ],
    weatherTheme: 'windy',
    airCurrentTheme: 'turbulent',
    backgroundStory: '强劲的海风呼啸而过，天空中乌云密布。只有真正的勇士才能在这样的天气中翱翔。',
    timeLimit: 180,
    totalRewardScore: 5000,
    totalRewardCoins: 250,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
  },
  {
    id: 'stage-4',
    name: '暗夜翱翔',
    description: '极限赛段，在夜空中挑战自我',
    stageNumber: 4,
    chapterId: 'chapter-3',
    tasks: [
      createTask('s4-t1', '暗夜长征', '飞行距离达到 5000 米', 'distanceTarget', 5000, 'extreme', 2000, 100),
      createTask('s4-t2', '星辰之顶', '达到 350 米高度', 'heightTarget', 350, 'extreme', 2500, 120),
      createTask('s4-t3', '气流之王', '捕获 100 个气流', 'airCurrentCount', 100, 'extreme', 2200, 110),
      createTask('s4-t4', '完美飞行', '得分达到 8000 分', 'scoreTarget', 8000, 'extreme', 1800, 90),
      createTask('s4-t5', '终极连击', '连续捕获 30 个气流不中断', 'comboAirCurrent', 30, 'extreme', 2000, 100),
      createTask('s4-t6', '生存大师', '存活 200 秒', 'timeSurvival', 200, 'extreme', 1500, 80),
    ],
    weatherTheme: 'night',
    airCurrentTheme: 'extreme',
    backgroundStory: '夜幕降临，星空璀璨。在月光下飞行，感受风的低语，挑战你的极限！',
    timeLimit: 240,
    totalRewardScore: 12000,
    totalRewardCoins: 600,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
  },
  {
    id: 'stage-5',
    name: '传说之巅',
    description: '传说级赛段，只有真正的大师才能完成',
    stageNumber: 5,
    chapterId: 'chapter-4',
    tasks: [
      createTask('s5-t1', '万里鹏程', '飞行距离达到 8000 米', 'distanceTarget', 8000, 'extreme', 4000, 200),
      createTask('s5-t2', '九天揽月', '达到 500 米高度', 'heightTarget', 500, 'extreme', 5000, 250),
      createTask('s5-t3', '风之主宰', '捕获 200 个气流', 'airCurrentCount', 200, 'extreme', 4500, 225),
      createTask('s5-t4', '传说分数', '得分达到 20000 分', 'scoreTarget', 20000, 'extreme', 4000, 200),
      createTask('s5-t5', '完美连击', '连续捕获 50 个气流不中断', 'comboAirCurrent', 50, 'extreme', 4500, 225),
      createTask('s5-t6', '永恒飞行', '存活 300 秒', 'timeSurvival', 300, 'extreme', 3000, 150),
    ],
    weatherTheme: 'stormy',
    airCurrentTheme: 'extreme',
    backgroundStory: '风暴之巅，雷电交加。传说只有风筝之神才能在这样的天气中自由翱翔。你准备好了吗？',
    timeLimit: 300,
    totalRewardScore: 25000,
    totalRewardCoins: 1250,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
  },
];

export const getStageById = (id: string): Stage | undefined => {
  return STAGES.find(s => s.id === id);
};

export const getStages = (): Stage[] => {
  return [...STAGES];
};

export const getChapterById = (id: string): Chapter | undefined => {
  return CHAPTERS.find(c => c.id === id);
};

export const getChapters = (): Chapter[] => {
  return JSON.parse(JSON.stringify(CHAPTERS));
};
