import type { LevelScene, GlobalSettings } from './types';

const now = Date.now();

const DEFAULT_GLOBAL_SETTINGS: GlobalSettings = {
  gravity: 0.015,
  windSpeed: 0.3,
  turbulence: 0.1,
};

const createBuilding = (b: any) => ({
  ...b,
  size: { x: b.width, y: b.height, z: b.depth },
});

const createObjective = (obj: any) => ({
  ...obj,
  completed: false,
  targetScore: obj.targetValue,
  targetTime: obj.targetValue,
  targetDistance: obj.targetValue,
  targetHeight: obj.targetValue,
});

const createLoseCondition = (type: 'timeOut' | 'crash' | 'scoreBelow', options: any = {}) => ({
  type,
  enabled: true,
  ...options,
});

export const PRESET_LEVELS: LevelScene[] = [
  {
    id: 'level_preset_1',
    name: '新手训练场',
    description: '适合初学者的简单关卡，学习基本操控技巧，穿越两座标志性建筑之间。',
    category: 'preset',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    globalSettings: { ...DEFAULT_GLOBAL_SETTINGS },
    buildings: [
      createBuilding({
        id: 'building_1',
        position: { x: -50, y: 25, z: -100 },
        width: 30,
        height: 50,
        depth: 30,
        color: 0x4682b4,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_2',
        position: { x: 50, y: 30, z: -100 },
        width: 30,
        height: 60,
        depth: 30,
        color: 0x696969,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_3',
        position: { x: 0, y: 40, z: -250 },
        width: 40,
        height: 80,
        depth: 40,
        color: 0x8b4513,
        isCollidable: true,
      }),
    ],
    airCurrents: [
      {
        id: 'air_1',
        position: { x: 0, y: 60, z: -150 },
        radius: 40,
        strength: 0.15,
        direction: { x: 0, y: 0.15, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_2',
        position: { x: -80, y: 80, z: -200 },
        radius: 35,
        strength: 0.12,
        direction: { x: 0, y: 0.12, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
    ],
    objectives: [
      createObjective({
        id: 'obj_1',
        type: 'reachPoint',
        name: '穿越两座大楼',
        description: '穿过两座蓝色大楼之间的空域',
        position: { x: 0, y: 55, z: -100 },
        radius: 30,
        completed: false,
      }),
      createObjective({
        id: 'obj_2',
        type: 'heightTarget',
        name: '达到100米高度',
        description: '风筝飞行高度达到100米',
        targetValue: 100,
        targetHeight: 100,
        completed: false,
      }),
    ],
    winCondition: {
      type: 'allObjectives',
    },
    loseCondition: createLoseCondition('crash'),
    gameConfig: {
      worldSize: 400,
      gravity: 0.015,
      airCurrentSpawnRate: 0,
      buildingDensity: 0,
    },
    weatherConfig: {
      windSpeed: 0.3,
      windDirection: { x: 0, y: 0, z: -0.5 },
      cloudCoverage: 0.3,
      timeOfDay: 0.5,
      turbulenceLevel: 0.1,
      timeOfDayFrozen: true,
    },
    startPosition: { x: 0, y: 80, z: 50 },
    icon: '🎯',
    difficulty: 'easy',
    tags: ['新手', '入门', '教程'],
  },
  {
    id: 'level_preset_2',
    name: '城市峡谷',
    description: '在高楼林立的城市峡谷中穿行，利用上升气流获得更高的分数。',
    category: 'preset',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    globalSettings: { ...DEFAULT_GLOBAL_SETTINGS, turbulence: 0.2 },
    buildings: [
      createBuilding({
        id: 'building_1',
        position: { x: -80, y: 50, z: -100 },
        width: 35,
        height: 100,
        depth: 35,
        color: 0x708090,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_2',
        position: { x: 80, y: 45, z: -100 },
        width: 35,
        height: 90,
        depth: 35,
        color: 0x708090,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_3',
        position: { x: -60, y: 60, z: -250 },
        width: 40,
        height: 120,
        depth: 40,
        color: 0x4682b4,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_4',
        position: { x: 60, y: 55, z: -250 },
        width: 40,
        height: 110,
        depth: 40,
        color: 0x4682b4,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_5',
        position: { x: 0, y: 70, z: -400 },
        width: 50,
        height: 140,
        depth: 50,
        color: 0x8b4513,
        isCollidable: true,
      }),
    ],
    airCurrents: [
      {
        id: 'air_1',
        position: { x: 0, y: 80, z: -175 },
        radius: 50,
        strength: 0.18,
        direction: { x: 0, y: 0.18, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_2',
        position: { x: 0, y: 100, z: -325 },
        radius: 45,
        strength: 0.2,
        direction: { x: 0, y: 0.2, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_3',
        position: { x: -120, y: 60, z: -180 },
        radius: 30,
        strength: 0.1,
        direction: { x: 0.1, y: -0.06, z: 0.1 },
        type: 'turbulence',
        isStatic: true,
      },
      {
        id: 'air_4',
        position: { x: 120, y: 60, z: -180 },
        radius: 30,
        strength: 0.1,
        direction: { x: -0.1, y: -0.06, z: 0.1 },
        type: 'turbulence',
        isStatic: true,
      },
    ],
    objectives: [
      createObjective({
        id: 'obj_1',
        type: 'reachPoint',
        name: '穿越一号峡谷',
        description: '穿过第一组高楼之间的峡谷',
        position: { x: 0, y: 80, z: -100 },
        radius: 40,
        completed: false,
      }),
      createObjective({
        id: 'obj_2',
        type: 'reachPoint',
        name: '穿越二号峡谷',
        description: '穿过第二组高楼之间的峡谷',
        position: { x: 0, y: 90, z: -250 },
        radius: 40,
        completed: false,
      }),
      createObjective({
        id: 'obj_3',
        type: 'scoreTarget',
        name: '获得500分',
        description: '飞行得分达到500分',
        targetValue: 500,
        targetScore: 500,
        completed: false,
      }),
    ],
    winCondition: {
      type: 'allObjectives',
    },
    loseCondition: createLoseCondition('crash'),
    gameConfig: {
      worldSize: 600,
      gravity: 0.015,
      airCurrentSpawnRate: 0,
      buildingDensity: 0,
    },
    weatherConfig: {
      windSpeed: 0.4,
      windDirection: { x: 0, y: 0, z: -0.6 },
      cloudCoverage: 0.4,
      timeOfDay: 0.5,
      turbulenceLevel: 0.2,
      timeOfDayFrozen: true,
    },
    startPosition: { x: 0, y: 80, z: 50 },
    icon: '🏙️',
    difficulty: 'medium',
    tags: ['城市', '峡谷', '气流'],
  },
  {
    id: 'level_preset_3',
    name: '时间挑战',
    description: '在60秒内获得尽可能高的分数，考验你的飞行效率。',
    category: 'preset',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    globalSettings: { ...DEFAULT_GLOBAL_SETTINGS, turbulence: 0.15 },
    buildings: [
      createBuilding({
        id: 'building_1',
        position: { x: -100, y: 30, z: -150 },
        width: 40,
        height: 60,
        depth: 40,
        color: 0xcd853f,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_2',
        position: { x: 100, y: 35, z: -150 },
        width: 40,
        height: 70,
        depth: 40,
        color: 0xcd853f,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_3',
        position: { x: 0, y: 40, z: -300 },
        width: 50,
        height: 80,
        depth: 50,
        color: 0xb8860b,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_4',
        position: { x: -120, y: 25, z: -400 },
        width: 35,
        height: 50,
        depth: 35,
        color: 0xd2b48c,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_5',
        position: { x: 120, y: 25, z: -400 },
        width: 35,
        height: 50,
        depth: 35,
        color: 0xd2b48c,
        isCollidable: true,
      }),
    ],
    airCurrents: [
      {
        id: 'air_1',
        position: { x: 0, y: 70, z: -150 },
        radius: 50,
        strength: 0.16,
        direction: { x: 0, y: 0.16, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_2',
        position: { x: -80, y: 90, z: -280 },
        radius: 40,
        strength: 0.18,
        direction: { x: 0, y: 0.18, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_3',
        position: { x: 80, y: 90, z: -280 },
        radius: 40,
        strength: 0.18,
        direction: { x: 0, y: 0.18, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_4',
        position: { x: 0, y: 100, z: -400 },
        radius: 60,
        strength: 0.22,
        direction: { x: 0, y: 0.22, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
    ],
    objectives: [
      createObjective({
        id: 'obj_1',
        type: 'timeLimit',
        name: '60秒时间挑战',
        description: '在60秒内获得尽可能高的分数',
        targetValue: 60,
        targetTime: 60,
        completed: false,
      }),
      createObjective({
        id: 'obj_2',
        type: 'scoreTarget',
        name: '获得800分',
        description: '在时间结束前获得800分',
        targetValue: 800,
        targetScore: 800,
        completed: false,
      }),
      createObjective({
        id: 'obj_3',
        type: 'distanceTarget',
        name: '飞行500米',
        description: '累计飞行距离达到500米',
        targetValue: 500,
        targetDistance: 500,
        completed: false,
      }),
    ],
    winCondition: {
      type: 'scoreThreshold',
      targetScore: 800,
    },
    loseCondition: createLoseCondition('timeOut', { timeLimit: 60 }),
    gameConfig: {
      worldSize: 600,
      gravity: 0.015,
      airCurrentSpawnRate: 0,
      buildingDensity: 0,
    },
    weatherConfig: {
      windSpeed: 0.35,
      windDirection: { x: 0, y: 0, z: -0.5 },
      cloudCoverage: 0.5,
      timeOfDay: 0.6,
      turbulenceLevel: 0.15,
      timeOfDayFrozen: true,
    },
    startPosition: { x: 0, y: 80, z: 50 },
    icon: '⏱️',
    difficulty: 'hard',
    tags: ['计时', '挑战', '高分'],
  },
  {
    id: 'level_preset_4',
    name: '极限湍流',
    description: '在极端湍流环境中飞行，考验你的风筝稳定性和操控技巧。',
    category: 'preset',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    globalSettings: {
      gravity: 0.018,
      windSpeed: 0.6,
      turbulence: 0.5,
    },
    buildings: [
      createBuilding({
        id: 'building_1',
        position: { x: -60, y: 50, z: -120 },
        width: 30,
        height: 100,
        depth: 30,
        color: 0x556b2f,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_2',
        position: { x: 60, y: 50, z: -120 },
        width: 30,
        height: 100,
        depth: 30,
        color: 0x556b2f,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_3',
        position: { x: -90, y: 60, z: -280 },
        width: 35,
        height: 120,
        depth: 35,
        color: 0x808080,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_4',
        position: { x: 90, y: 60, z: -280 },
        width: 35,
        height: 120,
        depth: 35,
        color: 0x808080,
        isCollidable: true,
      }),
      createBuilding({
        id: 'building_5',
        position: { x: 0, y: 75, z: -200 },
        width: 45,
        height: 150,
        depth: 45,
        color: 0x4682b4,
        isCollidable: true,
      }),
    ],
    airCurrents: [
      {
        id: 'air_1',
        position: { x: 0, y: 80, z: -80 },
        radius: 35,
        strength: 0.12,
        direction: { x: 0.1, y: 0.05, z: -0.1 },
        type: 'turbulence',
        isStatic: true,
      },
      {
        id: 'air_2',
        position: { x: -40, y: 60, z: -160 },
        radius: 30,
        strength: 0.15,
        direction: { x: -0.1, y: 0.08, z: 0.05 },
        type: 'turbulence',
        isStatic: true,
      },
      {
        id: 'air_3',
        position: { x: 40, y: 60, z: -160 },
        radius: 30,
        strength: 0.15,
        direction: { x: 0.1, y: 0.08, z: -0.05 },
        type: 'turbulence',
        isStatic: true,
      },
      {
        id: 'air_4',
        position: { x: 0, y: 120, z: -250 },
        radius: 45,
        strength: 0.2,
        direction: { x: 0, y: 0.2, z: 0 },
        type: 'updraft',
        isStatic: true,
      },
      {
        id: 'air_5',
        position: { x: -60, y: 100, z: -350 },
        radius: 25,
        strength: 0.1,
        direction: { x: 0, y: -0.06, z: 0 },
        type: 'downdraft',
        isStatic: true,
      },
      {
        id: 'air_6',
        position: { x: 60, y: 100, z: -350 },
        radius: 25,
        strength: 0.1,
        direction: { x: 0, y: -0.06, z: 0 },
        type: 'downdraft',
        isStatic: true,
      },
    ],
    objectives: [
      createObjective({
        id: 'obj_1',
        type: 'reachPoint',
        name: '穿越湍流区',
        description: '成功穿过中心湍流区域',
        position: { x: 0, y: 100, z: -200 },
        radius: 50,
        completed: false,
      }),
      createObjective({
        id: 'obj_2',
        type: 'heightTarget',
        name: '达到150米高度',
        description: '在湍流中保持足够的高度',
        targetValue: 150,
        targetHeight: 150,
        completed: false,
      }),
      createObjective({
        id: 'obj_3',
        type: 'scoreTarget',
        name: '获得1000分',
        description: '在极端环境中获得1000分',
        targetValue: 1000,
        targetScore: 1000,
        completed: false,
      }),
    ],
    winCondition: {
      type: 'allObjectives',
    },
    loseCondition: createLoseCondition('crash'),
    gameConfig: {
      worldSize: 500,
      gravity: 0.018,
      airCurrentSpawnRate: 0,
      buildingDensity: 0,
    },
    weatherConfig: {
      windSpeed: 0.6,
      windDirection: { x: 0.2, y: 0, z: -0.6 },
      cloudCoverage: 0.7,
      timeOfDay: 0.7,
      turbulenceLevel: 0.5,
      timeOfDayFrozen: true,
    },
    startPosition: { x: 0, y: 80, z: 50 },
    icon: '🌪️',
    difficulty: 'extreme',
    tags: ['湍流', '极限', '挑战'],
  },
];
