import type { KitePart } from './types';

export const ALL_PARTS: KitePart[] = [
  // ========== 风筝面 (Sail) ==========
  {
    id: 'sail_basic_red',
    name: '经典红鸢',
    description: '最传统的红色菱形风筝面，稳定可靠。',
    slot: 'sail',
    rarity: 'common',
    icon: '🪁',
    attributes: { lift: 5, stability: 5, speed: 0, durability: 10, maneuverability: 0, windResistance: 3 },
    visual: { color: '#ff4444', secondaryColor: '#cc3333' },
    unlocked: true,
    price: 0,
  },
  {
    id: 'sail_blue_sky',
    name: '蓝天之翼',
    description: '天蓝色风筝面，轻盈飘逸，提升升力。',
    slot: 'sail',
    rarity: 'uncommon',
    icon: '🪁',
    attributes: { lift: 12, stability: 3, speed: 2, durability: 6, maneuverability: 3, windResistance: 2 },
    visual: { color: '#4ecdc4', secondaryColor: '#3db8b0' },
    unlocked: false,
    price: 500,
  },
  {
    id: 'sail_golden_dragon',
    name: '金龙腾飞',
    description: '金色龙纹风筝面，气势非凡，全方位提升。',
    slot: 'sail',
    rarity: 'rare',
    icon: '🐉',
    attributes: { lift: 15, stability: 10, speed: 5, durability: 8, maneuverability: 5, windResistance: 8 },
    visual: { color: '#ffd700', secondaryColor: '#ff8c00' },
    unlocked: false,
    price: 1500,
  },
  {
    id: 'sail_phoenix',
    name: '凤凰涅槃',
    description: '火焰般的凤凰图案，速度与升力兼具。',
    slot: 'sail',
    rarity: 'epic',
    icon: '🔥',
    attributes: { lift: 20, stability: 8, speed: 15, durability: 10, maneuverability: 10, windResistance: 12 },
    visual: { color: '#ff6b35', secondaryColor: '#ff4444' },
    unlocked: false,
    price: 4000,
  },
  {
    id: 'sail_rainbow_legend',
    name: '彩虹传说',
    description: '传说中的七色风筝面，拥有神秘力量。',
    slot: 'sail',
    rarity: 'legendary',
    icon: '🌈',
    attributes: { lift: 25, stability: 20, speed: 18, durability: 15, maneuverability: 15, windResistance: 20 },
    visual: { color: '#ff69b4', secondaryColor: '#9370db' },
    unlocked: false,
    price: 10000,
  },

  // ========== 骨架 (Frame) ==========
  {
    id: 'frame_bamboo',
    name: '竹制骨架',
    description: '传统竹制骨架，轻便灵活。',
    slot: 'frame',
    rarity: 'common',
    icon: '🎋',
    attributes: { lift: 0, stability: 8, speed: 3, durability: 5, maneuverability: 5, windResistance: 2 },
    visual: { color: '#8b4513' },
    unlocked: true,
    price: 0,
  },
  {
    id: 'frame_carbon',
    name: '碳纤维骨架',
    description: '高强度碳纤维骨架，轻量且坚固。',
    slot: 'frame',
    rarity: 'rare',
    icon: '⚫',
    attributes: { lift: 3, stability: 12, speed: 8, durability: 15, maneuverability: 10, windResistance: 10 },
    visual: { color: '#2d2d2d' },
    unlocked: false,
    price: 2000,
  },
  {
    id: 'frame_titanium',
    name: '钛合金骨架',
    description: '航天级钛合金，极致强度与韧性。',
    slot: 'frame',
    rarity: 'epic',
    icon: '⚙️',
    attributes: { lift: 5, stability: 18, speed: 10, durability: 25, maneuverability: 12, windResistance: 15 },
    visual: { color: '#c0c0c0' },
    unlocked: false,
    price: 5000,
  },

  // ========== 尾巴 (Tail) ==========
  {
    id: 'tail_short_ribbon',
    name: '短飘带',
    description: '简约的短飘带尾巴，轻巧灵活。',
    slot: 'tail',
    rarity: 'common',
    icon: '🎀',
    attributes: { lift: 0, stability: 5, speed: 2, durability: 5, maneuverability: 8, windResistance: 0 },
    visual: { tailLength: 10, color: '#ff6b6b' },
    unlocked: true,
    price: 0,
  },
  {
    id: 'tail_long_streamer',
    name: '长尾飘带',
    description: '长长的彩色飘带，大幅提升稳定性。',
    slot: 'tail',
    rarity: 'uncommon',
    icon: '🎗️',
    attributes: { lift: 2, stability: 15, speed: -3, durability: 8, maneuverability: -2, windResistance: 5 },
    visual: { tailLength: 25, color: '#4ecdc4' },
    unlocked: false,
    price: 600,
  },
  {
    id: 'tail_snake_dragon',
    name: '龙蛇之尾',
    description: '如龙蛇般蜿蜒的长尾，气势磅礴。',
    slot: 'tail',
    rarity: 'rare',
    icon: '🐍',
    attributes: { lift: 5, stability: 20, speed: -2, durability: 12, maneuverability: 3, windResistance: 8 },
    visual: { tailLength: 35, color: '#22c55e' },
    unlocked: false,
    price: 1800,
  },
  {
    id: 'tail_phoenix_tail',
    name: '凤尾翎羽',
    description: '凤凰尾羽般华丽，传说中的神奇尾巴。',
    slot: 'tail',
    rarity: 'legendary',
    icon: '🦚',
    attributes: { lift: 12, stability: 25, speed: 5, durability: 18, maneuverability: 10, windResistance: 15 },
    visual: { tailLength: 40, color: '#ffd700' },
    unlocked: false,
    price: 8000,
  },

  // ========== 风筝线 (String) ==========
  {
    id: 'string_cotton',
    name: '棉线',
    description: '传统棉线，经济实惠。',
    slot: 'string',
    rarity: 'common',
    icon: '🧵',
    attributes: { lift: 0, stability: 3, speed: 0, durability: 8, maneuverability: 2, windResistance: 2 },
    visual: { color: '#f5f5dc' },
    unlocked: true,
    price: 0,
  },
  {
    id: 'string_nylon',
    name: '尼龙线',
    description: '高强度尼龙线，结实耐用。',
    slot: 'string',
    rarity: 'uncommon',
    icon: '🪢',
    attributes: { lift: 0, stability: 5, speed: 2, durability: 15, maneuverability: 5, windResistance: 5 },
    visual: { color: '#87ceeb' },
    unlocked: false,
    price: 400,
  },
  {
    id: 'string_kevlar',
    name: '凯夫拉线',
    description: '军工级凯夫拉材质，几乎无法拉断。',
    slot: 'string',
    rarity: 'epic',
    icon: '💎',
    attributes: { lift: 2, stability: 10, speed: 5, durability: 30, maneuverability: 12, windResistance: 12 },
    visual: { color: '#ffd700' },
    unlocked: false,
    price: 4500,
  },

  // ========== 装饰 (Decoration) ==========
  {
    id: 'deco_bell',
    name: '风铃',
    description: '清脆的风铃装饰，随风作响。',
    slot: 'decoration',
    rarity: 'common',
    icon: '🔔',
    attributes: { lift: 0, stability: 2, speed: -1, durability: 5, maneuverability: 0, windResistance: 1 },
    visual: {},
    unlocked: true,
    price: 0,
  },
  {
    id: 'deco_feather',
    name: '羽毛挂饰',
    description: '轻盈的羽毛装饰，增添灵动。',
    slot: 'decoration',
    rarity: 'uncommon',
    icon: '🪶',
    attributes: { lift: 3, stability: 3, speed: 2, durability: 3, maneuverability: 5, windResistance: 2 },
    visual: {},
    unlocked: false,
    price: 300,
  },
  {
    id: 'deco_lucky_charm',
    name: '幸运符',
    description: '神秘的幸运符，带来好运和额外分数。',
    slot: 'decoration',
    rarity: 'rare',
    icon: '🍀',
    attributes: { lift: 2, stability: 5, speed: 0, durability: 10, maneuverability: 3, windResistance: 5 },
    visual: {},
    unlocked: false,
    price: 1200,
  },
  {
    id: 'deco_star_crystal',
    name: '星辰水晶',
    description: '闪烁的星辰水晶，蕴含宇宙能量。',
    slot: 'decoration',
    rarity: 'legendary',
    icon: '✨',
    attributes: { lift: 10, stability: 12, speed: 8, durability: 15, maneuverability: 10, windResistance: 12 },
    visual: {},
    unlocked: false,
    price: 12000,
  },
];

export const INITIAL_PART_IDS = ['sail_basic_red', 'frame_bamboo', 'tail_short_ribbon', 'string_cotton', 'deco_bell'];
