import type { ChapterConfig, LessonConfig } from './types';

export const CHAPTERS: ChapterConfig[] = [
  {
    id: 'chapter_basic',
    name: '第一章 · 基础操控',
    description: '学习风筝飞行的基本操作，掌握起飞、转向和保持平衡',
    icon: '🎮',
    order: 1,
    unlockChapterId: null,
    lessonIds: ['lesson_basic_01', 'lesson_basic_02', 'lesson_basic_exam'],
    requiredCompletions: 3,
    completionCoinBonus: 200,
  },
  {
    id: 'chapter_air',
    name: '第二章 · 气流识别',
    description: '学会识别和利用上升气流，在天空中自由翱翔',
    icon: '🌬️',
    order: 2,
    unlockChapterId: 'chapter_basic',
    lessonIds: ['lesson_air_01', 'lesson_air_02', 'lesson_air_exam'],
    requiredCompletions: 3,
    completionCoinBonus: 300,
  },
  {
    id: 'chapter_risk',
    name: '第三章 · 风险应对',
    description: '了解飞行中的风险与危险，学会在复杂环境中安全飞行',
    icon: '⚠️',
    order: 3,
    unlockChapterId: 'chapter_air',
    lessonIds: ['lesson_risk_01', 'lesson_risk_02', 'lesson_risk_exam'],
    requiredCompletions: 3,
    completionCoinBonus: 400,
  },
];

export const LESSONS: LessonConfig[] = [
  {
    id: 'lesson_basic_01',
    type: 'basic_controls',
    name: '1-1 起飞与升降',
    description: '学习如何让风筝起飞并控制高度',
    icon: '🚀',
    chapterId: 'chapter_basic',
    order: 1,
    unlockLessonId: null,
    passScore: 300,
    masterScore: 800,
    coinReward: 50,
    timeLimit: 90,
    worldSize: 350,
    gravity: 0.01,
    airCurrentSpawnRate: 0.04,
    minAirCurrentStrength: 0.05,
    maxAirCurrentStrength: 0.12,
    minBuildingHeight: 8,
    maxBuildingHeight: 30,
    buildingDensity: 0.15,
    windSpeed: 0.1,
    turbulenceLevel: 0.05,
    cloudCoverage: 0.2,
    tutorials: [
      {
        id: 'basic_01_step_01',
        type: 'info',
        title: '欢迎来到风筝训练营！',
        content: '在本课程中，你将学习风筝飞行的基础操作。让我们从最简单的起飞开始吧！',
        tips: ['保持耐心，熟练掌握基础是成为高手的关键'],
      },
      {
        id: 'basic_01_step_02',
        type: 'info',
        title: '认识操控键位',
        content: '使用 W/↑ 键让风筝上升，S/↓ 键下降。左右方向键或 A/D 控制转向。',
        tips: ['W/↑ 上升', 'S/↓ 下降', 'A/← 左转', 'D/→ 右转'],
      },
      {
        id: 'basic_01_step_03',
        type: 'demo',
        title: '观察风筝起飞',
        content: '当游戏开始时，风筝会自动起飞。尝试按上升键让它飞得更高！',
        tips: ['注意不要让风筝飞得太高或太低'],
      },
      {
        id: 'basic_01_step_04',
        type: 'interactive',
        title: '练习升降控制',
        content: '现在请开始游戏，练习让风筝上升到合适的高度（80-150米之间）。',
        interactiveAction: 'start_game',
        tips: ['保持稳定的高度是飞行的基础'],
      },
    ],
    examObjectives: [
      { id: 'obj_height', name: '达到高度', description: '最大高度超过80米', targetValue: 80, metric: 'height', weight: 30 },
      { id: 'obj_distance', name: '飞行距离', description: '飞行距离超过500米', targetValue: 500, metric: 'distance', weight: 30 },
      { id: 'obj_stability', name: '飞行稳定', description: '飞行稳定性大于0.7', targetValue: 0.7, metric: 'flightStability', weight: 40 },
    ],
  },
  {
    id: 'lesson_basic_02',
    type: 'basic_controls',
    name: '1-2 转向与平衡',
    description: '掌握左右转向，在城市中穿梭',
    icon: '↪️',
    chapterId: 'chapter_basic',
    order: 2,
    unlockLessonId: 'lesson_basic_01',
    passScore: 400,
    masterScore: 1000,
    coinReward: 80,
    timeLimit: 100,
    worldSize: 400,
    gravity: 0.012,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.06,
    maxAirCurrentStrength: 0.14,
    minBuildingHeight: 12,
    maxBuildingHeight: 40,
    buildingDensity: 0.25,
    windSpeed: 0.15,
    turbulenceLevel: 0.1,
    cloudCoverage: 0.25,
    tutorials: [
      {
        id: 'basic_02_step_01',
        type: 'info',
        title: '学习转向',
        content: '使用 A/← 键向左转，D/→ 键向右转。转向时要注意不要急转，保持流畅。',
        tips: ['转向幅度过大会导致风筝失速', '平滑的转向可以保持高度'],
      },
      {
        id: 'basic_02_step_02',
        type: 'info',
        title: '建筑物是障碍',
        content: '城市中的建筑物会阻挡风筝的飞行，撞到建筑会造成碰撞惩罚。',
        tips: ['尽量保持在开阔区域飞行', '提前规划好转向时机'],
      },
      {
        id: 'basic_02_step_03',
        type: 'interactive',
        title: '开始练习',
        content: '现在开始游戏，练习在建筑物之间穿梭，尽量避免碰撞！',
        interactiveAction: 'start_game',
        tips: ['保持足够的高度可以避开大部分建筑'],
      },
    ],
    examObjectives: [
      { id: 'obj_distance', name: '飞行距离', description: '飞行距离超过800米', targetValue: 800, metric: 'distance', weight: 30 },
      { id: 'obj_collision', name: '避免碰撞', description: '碰撞次数不超过2次', targetValue: 2, metric: 'collisions', weight: 30, isPenalty: true },
      { id: 'obj_stability', name: '飞行稳定', description: '飞行稳定性大于0.6', targetValue: 0.6, metric: 'flightStability', weight: 40 },
    ],
  },
  {
    id: 'lesson_basic_exam',
    type: 'exam',
    name: '1-3 基础考核',
    description: '检验你对基础操作的掌握程度',
    icon: '📝',
    chapterId: 'chapter_basic',
    order: 3,
    unlockLessonId: 'lesson_basic_02',
    passScore: 600,
    masterScore: 1500,
    coinReward: 150,
    timeLimit: 120,
    worldSize: 450,
    gravity: 0.013,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.06,
    maxAirCurrentStrength: 0.15,
    minBuildingHeight: 10,
    maxBuildingHeight: 50,
    buildingDensity: 0.3,
    windSpeed: 0.18,
    turbulenceLevel: 0.12,
    cloudCoverage: 0.3,
    tutorials: [
      {
        id: 'basic_exam_step_01',
        type: 'info',
        title: '基础操作考核',
        content: '这是第一阶段的考核！请展示你学到的基础操作技能，完成所有目标即可通过。',
        tips: ['保持高度稳定', '避开建筑物', '飞得越远分数越高'],
      },
      {
        id: 'basic_exam_step_02',
        type: 'interactive',
        title: '开始考核',
        content: '准备好了吗？点击开始，完成考核目标！',
        interactiveAction: 'start_game',
        tips: ['深呼吸，你已经准备好了！'],
      },
    ],
    examObjectives: [
      { id: 'obj_score', name: '综合得分', description: '总分达到600分以上', targetValue: 600, metric: 'score', weight: 40 },
      { id: 'obj_height', name: '最大高度', description: '最大高度超过100米', targetValue: 100, metric: 'height', weight: 20 },
      { id: 'obj_distance', name: '飞行距离', description: '飞行距离超过1000米', targetValue: 1000, metric: 'distance', weight: 20 },
      { id: 'obj_collision', name: '安全飞行', description: '碰撞次数不超过1次', targetValue: 1, metric: 'collisions', weight: 20, isPenalty: true },
    ],
  },
  {
    id: 'lesson_air_01',
    type: 'air_current',
    name: '2-1 认识气流',
    description: '学习识别上升气流，获取额外升力',
    icon: '💨',
    chapterId: 'chapter_air',
    order: 1,
    unlockLessonId: null,
    passScore: 500,
    masterScore: 1200,
    coinReward: 80,
    timeLimit: 90,
    worldSize: 450,
    gravity: 0.014,
    airCurrentSpawnRate: 0.045,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.18,
    minBuildingHeight: 15,
    maxBuildingHeight: 45,
    buildingDensity: 0.2,
    windSpeed: 0.2,
    turbulenceLevel: 0.15,
    cloudCoverage: 0.35,
    tutorials: [
      {
        id: 'air_01_step_01',
        type: 'info',
        title: '什么是上升气流？',
        content: '上升气流是自然上升的暖空气柱。当风筝进入上升气流时，会获得额外的升力帮助你飞得更高！',
        tips: ['气流在游戏中以光柱形式显示', '在气流中停留可以持续获得升力'],
      },
      {
        id: 'air_01_step_02',
        type: 'demo',
        title: '观察气流位置',
        content: '注意观察游戏中的光柱，那些就是上升气流。尝试飞进去感受一下！',
        tips: ['气流位置会随时间变化', '较强的气流颜色更亮'],
      },
      {
        id: 'air_01_step_03',
        type: 'interactive',
        title: '追逐气流',
        content: '现在开始游戏，尝试找到并穿越至少3个上升气流！',
        interactiveAction: 'start_game',
        tips: ['主动寻找气流可以大大提升飞行效率'],
      },
    ],
    examObjectives: [
      { id: 'obj_aircount', name: '气流捕获', description: '捕获至少3个气流', targetValue: 3, metric: 'airCurrentCount', weight: 40 },
      { id: 'obj_height', name: '利用气流升高', description: '最大高度超过120米', targetValue: 120, metric: 'height', weight: 30 },
      { id: 'obj_distance', name: '飞行距离', description: '飞行距离超过800米', targetValue: 800, metric: 'distance', weight: 30 },
    ],
  },
  {
    id: 'lesson_air_02',
    type: 'air_current',
    name: '2-2 影子追踪',
    description: '学习追踪风筝的影子，获得额外分数',
    icon: '🌤️',
    chapterId: 'chapter_air',
    order: 2,
    unlockLessonId: 'lesson_air_01',
    passScore: 600,
    masterScore: 1500,
    coinReward: 100,
    timeLimit: 100,
    worldSize: 500,
    gravity: 0.015,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 18,
    maxBuildingHeight: 55,
    buildingDensity: 0.28,
    windSpeed: 0.25,
    turbulenceLevel: 0.2,
    cloudCoverage: 0.5,
    tutorials: [
      {
        id: 'air_02_step_01',
        type: 'info',
        title: '影子追踪系统',
        content: '风筝在地面上会投下影子。保持影子追踪值越高，获得的分数加成就越多！',
        tips: ['影子追踪值在HUD上显示', '保持在光影最佳位置可以最大化得分'],
      },
      {
        id: 'air_02_step_02',
        type: 'info',
        title: '如何提高影子追踪',
        content: '保持风筝在合适的高度和位置，让影子清晰可见。云层会影响影子质量。',
        tips: ['天气晴朗时影子更清晰', '避免飞得过高，影子会变得模糊'],
      },
      {
        id: 'air_02_step_03',
        type: 'interactive',
        title: '练习影子追踪',
        content: '现在开始游戏，尽量保持高影子追踪值飞行！',
        interactiveAction: 'start_game',
        tips: ['影子追踪是高分玩家的必备技能'],
      },
    ],
    examObjectives: [
      { id: 'obj_shadow', name: '影子追踪', description: '平均影子追踪大于0.6', targetValue: 0.6, metric: 'shadowTracking', weight: 40 },
      { id: 'obj_aircount', name: '气流捕获', description: '捕获至少4个气流', targetValue: 4, metric: 'airCurrentCount', weight: 30 },
      { id: 'obj_score', name: '综合得分', description: '总分达到500分以上', targetValue: 500, metric: 'score', weight: 30 },
    ],
  },
  {
    id: 'lesson_air_exam',
    type: 'exam',
    name: '2-3 气流考核',
    description: '检验你对气流识别和利用的掌握',
    icon: '🌪️',
    chapterId: 'chapter_air',
    order: 3,
    unlockLessonId: 'lesson_air_02',
    passScore: 900,
    masterScore: 2000,
    coinReward: 200,
    timeLimit: 120,
    worldSize: 520,
    gravity: 0.016,
    airCurrentSpawnRate: 0.04,
    minAirCurrentStrength: 0.1,
    maxAirCurrentStrength: 0.22,
    minBuildingHeight: 15,
    maxBuildingHeight: 60,
    buildingDensity: 0.3,
    windSpeed: 0.3,
    turbulenceLevel: 0.25,
    cloudCoverage: 0.55,
    tutorials: [
      {
        id: 'air_exam_step_01',
        type: 'info',
        title: '气流识别考核',
        content: '这是第二阶段的考核！综合利用气流和影子追踪，获得高分吧！',
        tips: ['主动寻找气流', '保持影子追踪', '平衡高度与距离'],
      },
      {
        id: 'air_exam_step_02',
        type: 'interactive',
        title: '开始考核',
        content: '准备好了吗？点击开始，完成考核目标！',
        interactiveAction: 'start_game',
        tips: ['气流+影子追踪=高分秘籍！'],
      },
    ],
    examObjectives: [
      { id: 'obj_score', name: '综合得分', description: '总分达到900分以上', targetValue: 900, metric: 'score', weight: 35 },
      { id: 'obj_aircount', name: '气流捕获', description: '捕获至少5个气流', targetValue: 5, metric: 'airCurrentCount', weight: 25 },
      { id: 'obj_shadow', name: '影子追踪', description: '平均影子追踪大于0.7', targetValue: 0.7, metric: 'shadowTracking', weight: 25 },
      { id: 'obj_height', name: '最大高度', description: '最大高度超过150米', targetValue: 150, metric: 'height', weight: 15 },
    ],
  },
  {
    id: 'lesson_risk_01',
    type: 'risk_demo',
    name: '3-1 认识风险',
    description: '了解乱流、下降气流等危险情况',
    icon: '⛈️',
    chapterId: 'chapter_risk',
    order: 1,
    unlockLessonId: null,
    passScore: 600,
    masterScore: 1400,
    coinReward: 100,
    timeLimit: 90,
    worldSize: 500,
    gravity: 0.018,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.1,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 20,
    maxBuildingHeight: 55,
    buildingDensity: 0.32,
    windSpeed: 0.4,
    turbulenceLevel: 0.35,
    cloudCoverage: 0.6,
    tutorials: [
      {
        id: 'risk_01_step_01',
        type: 'info',
        title: '飞行中的风险',
        content: '恶劣天气会带来各种风险：乱流会扰乱飞行，强风会把你吹偏，建筑物碰撞会扣分。',
        tips: ['注意HUD上的天气指示器', '乱流等级越高，飞行越不稳定'],
      },
      {
        id: 'risk_01_step_02',
        type: 'info',
        title: '碰撞惩罚',
        content: '撞到建筑物不仅会扣分，还会让风筝失去稳定性。尽量保持在开阔区域飞行！',
        tips: ['提前规划路线', '保持足够高度', '遇到乱流时保持冷静'],
      },
      {
        id: 'risk_01_step_03',
        type: 'interactive',
        title: '体验恶劣天气',
        content: '现在开始游戏，在较为恶劣的天气中飞行，体验风险并学习应对！',
        interactiveAction: 'start_game',
        tips: ['遇到乱流时小幅调整方向', '不要试图与强风对抗'],
      },
    ],
    examObjectives: [
      { id: 'obj_stability', name: '飞行稳定', description: '飞行稳定性大于0.5', targetValue: 0.5, metric: 'flightStability', weight: 35 },
      { id: 'obj_collision', name: '安全飞行', description: '碰撞次数不超过3次', targetValue: 3, metric: 'collisions', weight: 35, isPenalty: true },
      { id: 'obj_distance', name: '坚持飞行', description: '飞行距离超过700米', targetValue: 700, metric: 'distance', weight: 30 },
    ],
  },
  {
    id: 'lesson_risk_02',
    type: 'risk_demo',
    name: '3-2 应对策略',
    description: '学习在恶劣环境中保持稳定的技巧',
    icon: '🛡️',
    chapterId: 'chapter_risk',
    order: 2,
    unlockLessonId: 'lesson_risk_01',
    passScore: 700,
    masterScore: 1800,
    coinReward: 120,
    timeLimit: 100,
    worldSize: 550,
    gravity: 0.02,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.1,
    maxAirCurrentStrength: 0.24,
    minBuildingHeight: 22,
    maxBuildingHeight: 65,
    buildingDensity: 0.35,
    windSpeed: 0.5,
    turbulenceLevel: 0.45,
    cloudCoverage: 0.7,
    tutorials: [
      {
        id: 'risk_02_step_01',
        type: 'info',
        title: '稳定飞行的秘诀',
        content: '在恶劣天气中：1) 保持中等高度 2) 小幅转向 3) 利用上升气流恢复高度 4) 避开密集建筑区',
        tips: ['不要贪高，适中的高度最安全', '提前发现气流比临时应对更重要'],
      },
      {
        id: 'risk_02_step_02',
        type: 'info',
        title: '时间与效率',
        content: '在恶劣天气中，快速完成飞行也是一种策略。不要在危险区域停留太久！',
        tips: ['好的玩家知道何时进取何时保守', '平衡风险和收益是关键'],
      },
      {
        id: 'risk_02_step_03',
        type: 'interactive',
        title: '挑战暴风',
        content: '现在开始游戏，在更强的乱流中飞行，运用你学到的技巧！',
        interactiveAction: 'start_game',
        tips: ['相信你的直觉，你已经训练过了！'],
      },
    ],
    examObjectives: [
      { id: 'obj_stability', name: '飞行稳定', description: '飞行稳定性大于0.55', targetValue: 0.55, metric: 'flightStability', weight: 30 },
      { id: 'obj_collision', name: '安全飞行', description: '碰撞次数不超过2次', targetValue: 2, metric: 'collisions', weight: 30, isPenalty: true },
      { id: 'obj_score', name: '综合得分', description: '总分达到600分以上', targetValue: 600, metric: 'score', weight: 40 },
    ],
  },
  {
    id: 'lesson_risk_exam',
    type: 'exam',
    name: '3-3 综合考核',
    description: '最终考核——暴风飞行挑战！',
    icon: '🏆',
    chapterId: 'chapter_risk',
    order: 3,
    unlockLessonId: 'lesson_risk_02',
    passScore: 1200,
    masterScore: 2500,
    coinReward: 300,
    timeLimit: 120,
    worldSize: 600,
    gravity: 0.022,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.12,
    maxAirCurrentStrength: 0.28,
    minBuildingHeight: 25,
    maxBuildingHeight: 70,
    buildingDensity: 0.4,
    windSpeed: 0.55,
    turbulenceLevel: 0.55,
    cloudCoverage: 0.75,
    tutorials: [
      {
        id: 'risk_exam_step_01',
        type: 'info',
        title: '最终考核',
        content: '这是教学训练营的最终考核！综合运用你学到的所有技能，在暴风中获得高分吧！',
        tips: ['基础操控', '气流利用', '影子追踪', '风险规避'],
      },
      {
        id: 'risk_exam_step_02',
        type: 'interactive',
        title: '开始最终考核',
        content: '你已经准备好了！点击开始，证明你是真正的风筝飞行员！',
        interactiveAction: 'start_game',
        tips: ['加油，未来的风筝大师！'],
      },
    ],
    examObjectives: [
      { id: 'obj_score', name: '综合得分', description: '总分达到1200分以上', targetValue: 1200, metric: 'score', weight: 30 },
      { id: 'obj_distance', name: '飞行距离', description: '飞行距离超过1500米', targetValue: 1500, metric: 'distance', weight: 15 },
      { id: 'obj_height', name: '最大高度', description: '最大高度超过180米', targetValue: 180, metric: 'height', weight: 15 },
      { id: 'obj_aircount', name: '气流捕获', description: '捕获至少6个气流', targetValue: 6, metric: 'airCurrentCount', weight: 15 },
      { id: 'obj_collision', name: '安全飞行', description: '碰撞次数不超过2次', targetValue: 2, metric: 'collisions', weight: 15, isPenalty: true },
      { id: 'obj_stability', name: '飞行稳定', description: '飞行稳定性大于0.6', targetValue: 0.6, metric: 'flightStability', weight: 10 },
    ],
  },
];
