import type { LessonConfig, LessonProgress, LessonStatus } from './types';

export const LESSONS: LessonConfig[] = [
  {
    id: 'lesson_intro',
    phase: 'intro',
    type: 'basic',
    title: '欢迎来到风筝训练营',
    subtitle: '开启你的风筝之旅',
    icon: '🎓',
    color: '#6366f1',
    description: '在这个训练营中，你将学习风筝操控的核心技能，从基础操作到气流识别，再到风险规避与实战考核。完成全部训练后，你将成为一名合格的风筝飞行员！',
    steps: [
      {
        id: 'intro_1',
        title: '训练营介绍',
        description: '欢迎参加风筝飞行训练营！本课程将带你系统学习风筝飞行的各项技能。通过循序渐进的训练，你将掌握基础操作、气流识别、风险规避等核心能力，并通过分段考核获得丰厚奖励。',
        tips: [
          '按照课程顺序依次学习效果最佳',
          '每完成一个课程都会解锁下一个',
          '考核通过可获得金币奖励，用于工坊升级风筝',
        ],
        type: 'tutorial',
      },
      {
        id: 'intro_2',
        title: '操作指南总览',
        description: '在开始正式训练前，先熟悉一下基本的操作方式：\n\n• W / ↑ 键 - 拉升风筝高度\n• S / ↓ 键 - 降低风筝高度\n• A / ← 键 - 向左转向\n• D / → 键 - 向右转向\n• ESC / P 键 - 暂停游戏',
        tips: [
          '建议先在自由模式中熟悉操作',
          '平稳操作比激进操作更能保持飞行',
          '注意观察影子追踪度和飞行稳定性',
        ],
        type: 'tutorial',
      },
    ],
    coinReward: 0,
    unlockNextId: 'lesson_basic_1',
  },
  {
    id: 'lesson_basic_1',
    phase: 'basic_controls',
    type: 'basic',
    title: '第一阶段：基础操作',
    subtitle: '掌握风筝的起飞与转向',
    icon: '🎮',
    color: '#22c55e',
    description: '学习风筝的基本操控方式，包括起飞、保持高度、左右转向，以及如何平稳地控制风筝在空中飞行。',
    steps: [
      {
        id: 'basic_1_1',
        title: '起飞与高度控制',
        description: '使用 W 键或方向键 ↑ 可以让风筝上升，使用 S 键或方向键 ↓ 可以让风筝下降。\n\n要点：\n• 轻按 W 键可以获得稳定的上升\n• 按 S 键不要过久，避免风筝坠落\n• 保持适当高度，观察影子追踪度',
        tips: [
          '平稳上升比快速拉升更省风力',
          '高度过低会碰到建筑物',
          '高度过高可能进入稀薄空气区',
        ],
        type: 'tutorial',
      },
      {
        id: 'basic_1_2',
        title: '转向练习',
        description: '使用 A/D 键或方向键 ←/→ 控制风筝左右转向。转向时会略微损失高度，需要配合拉升操作。\n\n要点：\n• 转向时轻按，不要持续按住\n• 大角度转向后记得拉升\n• 提前预判障碍物位置',
        tips: [
          '转向时风筝会倾斜，适当拉升保持高度',
          '小幅度多次转向比大角度转向更稳定',
          '利用气流可以轻松转向',
        ],
        type: 'tutorial',
      },
      {
        id: 'basic_1_3',
        title: '平稳飞行挑战',
        description: '现在进行实际操作练习！在和风中稳定飞行 30 秒，保持高度在 60-120 之间，尽量不要碰到任何障碍物。',
        type: 'interactive',
        duration: 60,
        targetScore: 300,
      },
    ],
    coinReward: 50,
    unlockNextId: 'lesson_basic_2',
    worldSize: 350,
    gravity: 0.01,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.05,
    maxAirCurrentStrength: 0.12,
    minBuildingHeight: 8,
    maxBuildingHeight: 30,
    buildingDensity: 0.15,
    turbulenceLevel: 0.05,
    cloudCoverage: 0.2,
  },
  {
    id: 'lesson_basic_2',
    phase: 'basic_controls',
    type: 'basic',
    title: '进阶操控：速度与稳定',
    subtitle: '平衡速度与稳定性',
    icon: '⚡',
    color: '#10b981',
    description: '学习如何在保持稳定的前提下提升飞行速度，以及如何通过微调来维持最佳飞行状态。',
    steps: [
      {
        id: 'basic_2_1',
        title: '速度与稳定性的关系',
        description: '飞行速度越快，风筝越容易受到风力影响而变得不稳定。但速度过低也会导致升力不足。\n\n理想状态：\n• 稳定性指数保持在 0.8 以上\n• 适当加速可以获得更多距离分\n• 遇到乱流时减速保持稳定',
        tips: [
          '稳定性越高，得分加成越多',
          '可以通过轻微调整高度来控制速度',
          '气流区域内飞行速度更快更稳定',
        ],
        type: 'tutorial',
      },
      {
        id: 'basic_2_2',
        title: '影子追踪技巧',
        description: '注意屏幕上显示的影子追踪度（Shadow Tracking）。影子追踪度越高，说明风筝的位置越理想，得分加成也越高。\n\n提升影子追踪度：\n• 保持适中的飞行高度\n• 避免频繁大幅转向\n• 在气流区域内飞行',
        tips: [
          '影子追踪度 0.7 以上有显著得分加成',
          '稳定飞行可以逐步提高影子追踪度',
          '碰撞会大幅降低追踪度',
        ],
        type: 'tutorial',
      },
      {
        id: 'basic_2_3',
        title: '高效飞行挑战',
        description: '挑战在 90 秒内飞行尽可能远的距离，同时保持影子追踪度在 0.6 以上。目标分数：600 分。',
        type: 'challenge',
        duration: 90,
        targetScore: 600,
      },
    ],
    coinReward: 80,
    unlockNextId: 'lesson_airflow_1',
    requiredScore: 300,
    worldSize: 400,
    gravity: 0.012,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.06,
    maxAirCurrentStrength: 0.15,
    minBuildingHeight: 10,
    maxBuildingHeight: 35,
    buildingDensity: 0.2,
    turbulenceLevel: 0.1,
    cloudCoverage: 0.3,
  },
  {
    id: 'lesson_airflow_1',
    phase: 'airflow_recognition',
    type: 'airflow',
    title: '第二阶段：气流识别',
    subtitle: '读懂风的语言',
    icon: '🌬️',
    color: '#3b82f6',
    description: '上升气流是风筝飞行的能量来源。学习如何识别、追踪和利用气流，是成为高手的关键。',
    steps: [
      {
        id: 'airflow_1_1',
        title: '认识上升气流',
        description: '上升气流是游戏中的透明空气柱，颜色为淡蓝色。当风筝进入上升气流区域时：\n\n• 会获得额外的升力\n• 高度会自然上升\n• 飞行更加稳定\n• 获得气流捕获得分\n\n气流是随机出现的，注意观察天空！',
        tips: [
          '气流是得分的重要来源',
          '连续捕获多个气流会触发连击奖励',
          '气流会随时间消散，要及时利用',
        ],
        type: 'tutorial',
      },
      {
        id: 'airflow_1_2',
        title: '气流追踪技巧',
        description: '有效利用气流的技巧：\n\n1. 提前发现气流，调整方向飞向气流区\n2. 进入气流后适当减速，停留更长时间\n3. 在气流中可以轻松拉升高度\n4. 多个气流之间可以规划飞行路线',
        tips: [
          '气流通常成组出现，找到一个就能找到更多',
          '在气流中转向更省力',
          '利用气流高度可以避开下方建筑',
        ],
        type: 'tutorial',
      },
      {
        id: 'airflow_1_3',
        title: '气流猎人挑战',
        description: '在 90 秒内尽可能多地捕获上升气流。目标：捕获至少 5 个气流，得分达到 800 分。',
        type: 'challenge',
        duration: 90,
        targetScore: 800,
      },
    ],
    coinReward: 100,
    unlockNextId: 'lesson_airflow_2',
    requiredScore: 600,
    worldSize: 450,
    gravity: 0.013,
    airCurrentSpawnRate: 0.04,
    minAirCurrentStrength: 0.07,
    maxAirCurrentStrength: 0.18,
    minBuildingHeight: 12,
    maxBuildingHeight: 40,
    buildingDensity: 0.2,
    turbulenceLevel: 0.15,
    cloudCoverage: 0.35,
  },
  {
    id: 'lesson_airflow_2',
    phase: 'airflow_recognition',
    type: 'airflow',
    title: '高级气流：乱流与下降气流',
    subtitle: '识别危险气流区域',
    icon: '🌀',
    color: '#0ea5e9',
    description: '并非所有气流都是有利的。学会识别乱流和下降气流，避免进入危险区域。',
    steps: [
      {
        id: 'airflow_2_1',
        title: '认识乱流区',
        description: '乱流会让风筝变得不稳定，甚至失控。特征：\n\n• 风筝会出现不规则晃动\n• 稳定性指数快速下降\n• 可能出现非预期的高度变化\n\n应对方法：\n• 尽快飞出乱流区域\n• 减速保持稳定\n• 轻微调整方向',
        tips: [
          '云层较厚的区域乱流更多',
          '高空区域乱流更频繁',
          '稳定的风筝更能抵抗乱流',
        ],
        type: 'tutorial',
      },
      {
        id: 'airflow_2_2',
        title: '识别下降气流',
        description: '下降气流会把风筝往下拉，严重时可能导致坠落。\n\n识别方法：\n• 没有操作但高度持续下降\n• 升力明显减弱\n\n应对方法：\n• 持续按拉升键\n• 向气流区域飞行\n• 如果高度够高，可以快速穿过',
        tips: [
          '下降气流通常出现在背风面',
          '保持足够高度可以缓冲',
          '装备更好的风筝抗风性更强',
        ],
        type: 'tutorial',
      },
      {
        id: 'airflow_2_3',
        title: '气流大师挑战',
        description: '在多变的风场中飞行 120 秒，利用上升气流，避开乱流区域，稳定飞行。目标：1200 分，碰撞不超过 1 次。',
        type: 'challenge',
        duration: 120,
        targetScore: 1200,
      },
    ],
    coinReward: 150,
    unlockNextId: 'lesson_risk_1',
    requiredScore: 800,
    worldSize: 500,
    gravity: 0.014,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.06,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 15,
    maxBuildingHeight: 50,
    buildingDensity: 0.25,
    turbulenceLevel: 0.3,
    cloudCoverage: 0.5,
  },
  {
    id: 'lesson_risk_1',
    phase: 'risk_demo',
    type: 'risk',
    title: '第三阶段：风险演示',
    subtitle: '识别与规避飞行风险',
    icon: '⚠️',
    color: '#f59e0b',
    description: '了解风筝飞行中的各种风险因素，学习如何预防和应对危险情况，保障飞行安全。',
    steps: [
      {
        id: 'risk_1_1',
        title: '障碍物碰撞风险',
        description: '城市中的建筑物是最大的飞行障碍。碰撞会：\n\n• 扣除大量分数\n• 大幅降低影子追踪度\n• 严重时直接坠机\n\n规避技巧：\n• 保持足够的飞行高度\n• 提前观察前方建筑分布\n• 利用气流越过建筑群',
        tips: [
          '建筑物越高的区域风险越大',
          '可以通过影子判断建筑位置',
          '低空飞行要特别小心',
        ],
        type: 'tutorial',
      },
      {
        id: 'risk_1_2',
        title: '高度失控风险',
        description: '高度异常是常见的飞行事故原因：\n\n高度过低：\n• 容易碰撞建筑\n• 气流捕获机会减少\n• 影子追踪度下降\n\n高度过高：\n• 空气稀薄，升力不足\n• 乱流更频繁\n• 难以控制\n\n保持在 60-200 米的黄金区间',
        tips: [
          '看到建筑靠近就拉升',
          '高度超过 250 米时要留意',
          '进入气流区可以安全地获得高度',
        ],
        type: 'tutorial',
      },
      {
        id: 'risk_1_3',
        title: '天气风险应对',
        description: '不同天气条件的风险：\n\n• 多云/阴天：乱流增多，视线变差\n• 暴风天气：风速大，难以操控\n• 雷暴天气：极不稳定，建议避免\n\n应对策略：\n• 提前观察天气状况\n• 恶劣天气减速飞行\n• 保持更高的安全高度',
        tips: [
          '屏幕背景颜色反映天气状况',
          '好天气时抓紧刷分',
          '差天气时以稳定为主',
        ],
        type: 'tutorial',
      },
      {
        id: 'risk_1_4',
        title: '安全飞行挑战',
        description: '在建筑密集的城市中飞行 90 秒，实现零碰撞，保持高度稳定。目标：1000 分，稳定性 > 0.7。',
        type: 'challenge',
        duration: 90,
        targetScore: 1000,
      },
    ],
    coinReward: 120,
    unlockNextId: 'lesson_exam_1',
    requiredScore: 1200,
    worldSize: 480,
    gravity: 0.015,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.07,
    maxAirCurrentStrength: 0.18,
    minBuildingHeight: 15,
    maxBuildingHeight: 55,
    buildingDensity: 0.4,
    turbulenceLevel: 0.2,
    cloudCoverage: 0.4,
  },
  {
    id: 'lesson_exam_1',
    phase: 'segment_exam',
    type: 'exam',
    title: '第四阶段：分段考核（上）',
    subtitle: '基础与气流综合考核',
    icon: '📝',
    color: '#ef4444',
    description: '第一部分考核：检验你对基础操作和气流识别的掌握程度。通过考核可获得结业证书和金币奖励！',
    steps: [
      {
        id: 'exam_1_1',
        title: '考核说明',
        description: '本次考核将评估你在以下方面的能力：\n\n1. 基础操控（40%）：平稳飞行、精准转向\n2. 气流利用（40%）：捕获上升气流的数量和效率\n3. 风险规避（20%）：碰撞次数、稳定性\n\n考核规则：\n• 时间限制：120 秒\n• 及格分数：1500 分\n• 优秀分数：2500 分\n• 碰撞超过 2 次直接不合格',
        tips: [
          '先稳定飞行，不要急于求成',
          '看到气流优先捕获',
          '避开高密度建筑区域',
        ],
        type: 'tutorial',
      },
      {
        id: 'exam_1_2',
        title: '考核：基础与气流',
        description: '准备好了吗？开始第一部分考核！展示你学到的基础操作和气流识别技巧。',
        type: 'quiz',
        duration: 120,
        targetScore: 1500,
      },
    ],
    coinReward: 200,
    unlockNextId: 'lesson_exam_2',
    requiredScore: 1000,
    worldSize: 520,
    gravity: 0.015,
    airCurrentSpawnRate: 0.035,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.2,
    minBuildingHeight: 15,
    maxBuildingHeight: 50,
    buildingDensity: 0.3,
    turbulenceLevel: 0.25,
    cloudCoverage: 0.45,
  },
  {
    id: 'lesson_exam_2',
    phase: 'segment_exam',
    type: 'exam',
    title: '第四阶段：分段考核（下）',
    subtitle: '风险规避综合考核',
    icon: '📋',
    color: '#dc2626',
    description: '第二部分考核：在恶劣环境下检验你的风险规避能力。这是成为真正风筝飞行员的最终考验！',
    steps: [
      {
        id: 'exam_2_1',
        title: '考核说明',
        description: '本次考核将在复杂环境中评估你的综合能力：\n\n1. 风险识别：识别乱流和下降气流\n2. 应急处理：遇到突发状况的反应\n3. 综合操控：在恶劣条件下保持稳定飞行\n\n考核规则：\n• 时间限制：150 秒\n• 及格分数：2000 分\n• 优秀分数：3500 分\n• 碰撞超过 1 次直接不合格\n• 影子追踪度需保持在 0.5 以上',
        tips: [
          '这是最终考核，保持冷静',
          '以稳为主，不要贪分',
          '实在不行可以暂停思考',
        ],
        type: 'tutorial',
      },
      {
        id: 'exam_2_2',
        title: '最终考核：恶劣环境飞行',
        description: '最终挑战！在暴风天气的城市中飞行，证明你已经掌握了风筝飞行的全部技能。祝你好运！',
        type: 'quiz',
        duration: 150,
        targetScore: 2000,
      },
    ],
    coinReward: 300,
    unlockNextId: 'lesson_reward',
    requiredScore: 1500,
    worldSize: 550,
    gravity: 0.018,
    airCurrentSpawnRate: 0.03,
    minAirCurrentStrength: 0.08,
    maxAirCurrentStrength: 0.25,
    minBuildingHeight: 20,
    maxBuildingHeight: 60,
    buildingDensity: 0.35,
    turbulenceLevel: 0.45,
    cloudCoverage: 0.7,
  },
  {
    id: 'lesson_reward',
    phase: 'reward',
    type: 'reward',
    title: '第五阶段：毕业与奖励',
    subtitle: '恭喜你完成全部训练！',
    icon: '🎁',
    color: '#a855f7',
    description: '你已经完成了风筝训练营的全部课程！现在来领取你的毕业奖励吧。',
    steps: [
      {
        id: 'reward_1',
        title: '恭喜毕业！',
        description: '🎉 恭喜你完成了风筝训练营的全部课程！\n\n通过系统的训练，你已经掌握了：\n✅ 基础操控技能\n✅ 气流识别与利用\n✅ 风险识别与规避\n✅ 复杂环境飞行能力\n\n现在你是一名合格的风筝飞行员了！',
        tips: [
          '可以去工坊用金币升级你的风筝',
          '去赛事中心挑战更高难度的赛道',
          '不断练习，冲击高分榜！',
        ],
        type: 'tutorial',
      },
      {
        id: 'reward_2',
        title: '领取毕业奖励',
        description: '领取你的毕业奖励，包括：\n\n🎓 风筝飞行员结业证书\n🪙 额外 500 金币奖励\n🏆 解锁全部基础赛事赛道\n\n感谢你参加风筝训练营，祝你在天空中自由翱翔！',
        tips: [
          '点击下方按钮领取奖励',
          '奖励将自动添加到你的账户',
          '欢迎再来复习课程！',
        ],
        type: 'tutorial',
      },
    ],
    coinReward: 500,
    unlockNextId: null,
    requiredScore: 2000,
  },
];

export const DEFAULT_LESSON_PROGRESS = (lessonId: string, index: number): LessonProgress => ({
  lessonId,
  status: (index === 0 ? 'available' : 'locked') as LessonStatus,
  completedSteps: [],
  bestScore: 0,
  attempts: 0,
  completedAt: null,
});
